Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2021-08, with the labels that each got.

#6770 fix(footer): remove redux langDisplay
  packages/services-store/src/actions/__tests__/localeAPI.test.ts
  packages/services-store/src/actions/localeAPI.ts
  packages/services-store/src/reducers/__tests__/localeAPI.test.ts
  packages/services-store/src/reducers/localeAPI.ts
  packages/services-store/src/types/localeAPI.ts
  packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts
  packages/web-components/src/components/footer/footer-composite.ts
  packages/web-components/src/components/footer/footer-container.ts
  packages/web-components/src/components/locale-modal/locale-modal-composite.ts
  packages/web-components/src/components/locale-modal/locale-modal-container.ts
Labels: Ready to merge

#6777 fix(leadspace): set image and gradient to flip with RTL
  packages/styles/scss/components/leadspace/_leadspace.scss
Labels: RTL, Ready to merge

#6705 chore(VideoPlayerAPI): replacing references with KalturaPlayerAPI
  packages/react/config/jest/__mocks__/KalturaPlayerAPI.js
  packages/react/config/jest/setup.js
  packages/react/src/components/CTA/CardCTA.js
  packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js
  packages/react/src/components/VideoPlayer/README.stories.mdx
  packages/react/src/components/VideoPlayer/VideoImageOverlay.js
  packages/react/src/components/VideoPlayer/VideoPlayer.js
  packages/react/src/internal/hooks/useVideoData/__tests__/useVideoData.test.js
  packages/react/src/internal/hooks/useVideoData/useVideoData.js
  packages/services-store/src/actions/__tests__/videoPlayerAPI.test.ts
  packages/services-store/src/actions/kalturaPlayerAPI.ts
  packages/services-store/src/actions/videoPlayerAPI.ts
  packages/services-store/src/reducers/__tests__/kalturaPlayerAPi.test.ts
  packages/services-store/src/reducers/__tests__/videoPlayerAPi.test.ts
  packages/services-store/src/reducers/index.ts
  packages/services-store/src/reducers/kalturaPlayerAPI.ts
  packages/services-store/src/reducers/videoPlayerAPI.ts
  packages/services-store/src/types/kalturaPlayerAPI.ts
  packages/services-store/src/types/videoPlayerAPI.ts
  packages/services/src/services/KalturaPlayer/KalturaPlayer.js
  packages/services/src/services/VideoPlayer/VideoPlayer.js
  packages/services/src/services/VideoPlayer/__tests__/VideoPlayer.test.js
  packages/services/src/services/VideoPlayer/__tests__/data/response.json
  packages/services/src/services/index.js
  packages/web-components/src/components/cta/__stories__/README.stories.mdx
  packages/web-components/src/components/cta/__tests__/video-cta-composite.test.ts
  packages/web-components/src/components/cta/video-cta-composite.ts
  packages/web-components/src/components/cta/video-cta-container.ts
  packages/web-components/src/components/lightbox-media-viewer/__tests__/lightbox-media-viewer-container.test.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-container.ts
  packages/web-components/src/components/video-player/__stories__/README.stories.mdx
  packages/web-components/src/components/video-player/__tests__/video-player-container.test.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player-container.ts
  packages/web-components/tests/karma.conf.js
  packages/web-components/tests/mocks/KalturaPlayerAPI.ts
Labels: Ready to merge

#6780 chore(support): updating support roster for sprint 16
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/contribution_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: Ready to merge, dev

#6778 fix(feature-section): add the correct token for the background container
  packages/styles/scss/components/feature-section/_feature-section.scss
Labels: Ready to merge, adopter: AEM, package: web components

#6754 fix(back-to-top): update container tokens
  packages/styles/scss/components/back-to-top/_back-to-top.scss
Labels: Ready to merge, package: styles

#6786 docs(cookie-preferences): add documentation to set cookie preferences
  packages/react/src/components/Footer/README.stories.mdx
Labels: Ready to merge

#6788 fix(web-components): upgrade rollup to v2
  .yarn/offline-mirror/rollup-2.55.1.tgz
  packages/web-components/package.json
  yarn.lock
Labels: Ready to merge

#6793 fix(tabs-extended): ensure tab doesn't overlap with toc
  packages/styles/scss/components/tabs-extended/_tabs-extended.scss
Labels: Ready to merge, package: styles

#6806 fix(lead-space): fix to the lead space code sandbox example
  packages/web-components/examples/codesandbox/components/leadspace/assets/images/leadspace-sample-1.jpg
  packages/web-components/examples/codesandbox/components/leadspace/cdn.html
  packages/web-components/examples/codesandbox/components/leadspace/index.html
Labels: Ready to merge, dev

#6810 fix(leadspace): ensure leadspace image takes up entire width in lg bp
  packages/styles/scss/components/leadspace/_leadspace.scss
Labels: Ready to merge

#6809 fix(card-section-offset): background with 100%
  packages/styles/scss/components/card-section-offset/_card-section-offset.scss
Labels: Ready to merge

#6716 fix(tabs-extended): item token update
  packages/styles/scss/components/tabs-extended/_tabs-extended.scss
Labels: Ready to merge

#6731 feat(search-with-typeahead): introducing component
  packages/styles/scss/components/masthead/_masthead-top-nav-name.scss
  packages/styles/scss/components/masthead/_masthead.scss
  packages/styles/scss/components/masthead/index.scss
  packages/styles/scss/components/search-with-typeahead/_search-with-typeahead.scss
  packages/web-components/examples/codesandbox/components-react/search-with-typeahead/.gitignore
  packages/web-components/examples/codesandbox/components-react/search-with-typeahead/index.html
  packages/web-components/examples/codesandbox/components-react/search-with-typeahead/package.json
  packages/web-components/examples/codesandbox/components-react/search-with-typeahead/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/search-with-typeahead/src/index.css
  packages/web-components/examples/codesandbox/components-react/search-with-typeahead/src/index.js
  packages/web-components/examples/codesandbox/components-react/search-with-typeahead/webpack.config.js
  packages/web-components/examples/codesandbox/components/search-with-typeahead/.babelrc
  packages/web-components/examples/codesandbox/components/search-with-typeahead/.gitignore
  packages/web-components/examples/codesandbox/components/search-with-typeahead/.sassrc
  packages/web-components/examples/codesandbox/components/search-with-typeahead/cdn.html
  packages/web-components/examples/codesandbox/components/search-with-typeahead/index.html
  packages/web-components/examples/codesandbox/components/search-with-typeahead/package.json
  packages/web-components/examples/codesandbox/components/search-with-typeahead/sandbox.config.json
  packages/web-components/examples/codesandbox/components/search-with-typeahead/src/index.js
  packages/web-components/examples/codesandbox/components/search-with-typeahead/src/index.scss
  packages/web-components/src/components/filter-panel/filter-panel-checkbox.ts
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/masthead/__tests__/masthead-search-composite.test.ts
  packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
  packages/web-components/src/components/masthead/cloud/cloud-masthead-container.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/components/masthead/masthead-container-search-only.ts
  packages/web-components/src/components/masthead/masthead-container.ts
  packages/web-components/src/components/masthead/masthead-global-bar.ts
  packages/web-components/src/components/masthead/masthead-logo.ts
  packages/web-components/src/components/masthead/masthead-menu-button.ts
  packages/web-components/src/components/masthead/masthead-search-composite.ts
  packages/web-components/src/components/masthead/masthead-search-connect.ts
  packages/web-components/src/components/masthead/masthead-search-container.ts
  packages/web-components/src/components/masthead/masthead.scss
  packages/web-components/src/components/masthead/top-nav.ts
  packages/web-components/src/components/search-with-typeahead/__stories__/README.stories.mdx
  packages/web-components/src/components/search-with-typeahead/__stories__/README.stories.react.mdx
  packages/web-components/src/components/search-with-typeahead/__stories__/search-with-typeahead.stories.react.tsx
  packages/web-components/src/components/search-with-typeahead/__stories__/search-with-typeahead.stories.ts
  packages/web-components/src/components/search-with-typeahead/__tests__/search-with-typeahead.test.ts
  packages/web-components/src/components/search-with-typeahead/index.ts
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead-item.ts
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead.scss
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
  packages/web-components/tests/e2e/__tests__/search-with-typeahead/search-with-typeahead.cdn.e2e.js
  packages/web-components/tests/e2e/__tests__/search-with-typeahead/search-with-typeahead.e2e.js
  packages/web-components/tests/snapshots/dds-search-with-typeahead.md
Labels: Ready to merge

#6819 fix(locale): remove countrylist check for translation
  packages/services/src/services/Locale/Locale.js
  packages/services/src/services/Locale/__tests__/Locale.test.js
  packages/services/src/services/Translation/Translation.js
Labels: package: services, Ready to merge

#6769 fix(card): multiple style bugs
  packages/styles/scss/components/card-group/_card-group.scss
  packages/styles/scss/components/card/index.scss
Labels: Ready to merge

#6828 fix(masthead): react rtl overflow
  packages/react/src/components/Masthead/HeaderNavContainer.js
Labels: RTL, Ready to merge

#6836 fix(cloud-masthead): set position of masthead to fixed when expanded
  packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
Labels: feature flag, package: web components, Ready to merge

#6835 fix(masthead): flip megamenu link arrow icons in rtl
  packages/styles/scss/components/masthead/_masthead-megamenu.scss
  packages/web-components/src/components/masthead/cloud/cloud-masthead.scss
  packages/web-components/src/components/masthead/masthead.scss
Labels: RTL, Ready to merge

#6840 chore(deps): remove unused dependency
  .yarn/offline-mirror/is-port-reachable-3.0.0.tgz
  packages/react/package.json
  packages/web-components/package.json
  yarn.lock
Labels: Ready to merge

#6843 fix(card-in-card-5984): default to using Card component headline styling
  packages/styles/scss/components/card-in-card/_card-in-card.scss
Labels: package: web components, Ready to merge, adopter: AEM

#6864 fix(masthead): remove cloud masthead position fixing code
  packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
Labels: package: web components, Ready to merge

#6863 fix(CTA): allow onClick for buttonCTA to be passed
  packages/react/src/components/CTA/ButtonCTA.js
Labels: package: react, Ready to merge

#6866 chore(storybook): include knobs for react wrapper leadspace storybook
  packages/web-components/src/components/leadspace/__stories__/leadspace.stories.react.tsx
Labels: Ready to merge, storybook, :eyes: eyes needed

#6877 fix(video-player): set correct attribute name and state
  packages/web-components/src/components/cta/video-cta-composite.ts
  packages/web-components/src/components/cta/video-cta-container.ts
  packages/web-components/src/components/lightbox-media-viewer/__tests__/lightbox-video-player-composite.test.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts
  packages/web-components/src/components/video-player/__tests__/video-player-composite.test.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player-container.ts
Labels: package: web components, Ready to merge

#6885 fix(lightbox-media): check for kaltura onClose
  packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js
Labels: package: react, Ready to merge

#6865 fix(content-group-banner-6794): fix before pseudo-element bug on safari
  packages/styles/scss/components/content-group-banner/_content-group-banner.scss
Labels: package: web components, Ready to merge, adopter: AEM

#6881 feat(lightbox-media-viewer): style updates
  packages/styles/scss/components/expressive-modal/_expressive-modal.scss
  packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
  packages/web-components/src/components/expressive-modal/defs.ts
  packages/web-components/src/components/expressive-modal/expressive-modal.scss
  packages/web-components/src/components/expressive-modal/expressive-modal.ts
  packages/web-components/src/components/lightbox-media-viewer/__stories__/lightbox-media-viewer.stories.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts
  packages/web-components/tests/snapshots/dds-lightbox-video-player-composite.md
Labels: package: react, package: web components, Ready to merge, adopter: AEM

#6880 fix(dotcom-shell): ensure accurate ToC positioning, resolves #6172
  packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts
Labels: package: web components, Ready to merge, adopter: AEM

#6892 chore(support): updating support roster for sprint 17
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/contribution_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: dev, Ready to merge

#6841 fix(video-player): update hover and active state styles
  packages/styles/scss/components/video-player/_video-player.scss
Labels: package: react, package: styles, package: web components, Ready to merge

#6902 docs(web-components): update Code Sandbox default package version
  packages/web-components/examples/codesandbox/usage/webpack-basic/package.json
Labels: documentation, dev, Ready to merge

#6896 chore(plex): using shortened urls for CDN
  packages/utilities/src/utilities/loadNonLatinPlex/__tests__/loadNonLatinPlex.test.js
  packages/utilities/src/utilities/loadNonLatinPlex/loadNonLatinPlex.js
Labels: Ready to merge

#6895 feat(masthead): add custom profile login feature
  packages/services-store/src/types/translateAPI.ts
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/masthead/__stories__/profile-items.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/globals/internal/feature-flags.ts
Labels: feature flag, package: web components, Ready to merge

#6839 feat(card-link-copy): adding optional copy
  packages/styles/scss/components/card-link/_card-link.scss
  packages/web-components/src/components/card-link/__stories__/README.stories.mdx
  packages/web-components/src/components/card-link/__stories__/card-link.stories.ts
  packages/web-components/src/components/card-link/index.ts
Labels: package: web components, Ready to merge, adopter: AEM

#6906 fix(parcel): removing sass build in parcel for content-block-card-static
  packages/web-components/examples/codesandbox/components/content-block-card-static/.sassrc
  packages/web-components/examples/codesandbox/components/content-block-card-static/index.html
  packages/web-components/examples/codesandbox/components/content-block-card-static/package.json
  packages/web-components/examples/codesandbox/components/content-block-card-static/src/index.js
  packages/web-components/examples/codesandbox/components/content-block-card-static/src/index.scss
  packages/web-components/examples/codesandbox/components/content-block-cards/.sassrc
  packages/web-components/examples/codesandbox/components/content-block-cards/package.json
  packages/web-components/examples/codesandbox/components/content-block-cards/src/index.js
  packages/web-components/examples/codesandbox/components/content-block-cards/src/index.scss
Labels: dev, Ready to merge

#6900 feat(card-group): change same height util to apply to whole group instead of per row
  packages/react/src/components/CardGroup/CardGroup.js
  packages/web-components/src/components/card-group/card-group.ts
Labels: Ready to merge

#6908 docs(plex): adding documentation on Plex CDN
  packages/web-components/docs/carbon-cdn-style-helpers.md
Labels: Ready to merge

#6907 fix(cta-block): adjust header padding values to spec
  packages/styles/scss/components/cta-block/_cta-block.scss
  packages/web-components/src/components/cta-block/cta-block.scss
  packages/web-components/src/components/cta-section/cta-section.scss
Labels: package: styles, package: web components, Ready to merge

#6898 chore(analytics): deprecation of scroll tracker
  packages/react/.env.example
  packages/services/.env.example
  packages/services/src/services/Analytics/Analytics.js
  packages/services/src/services/Analytics/__tests__/Analytics.test.js
  packages/services/src/services/Locale/Locale.js
  packages/services/src/services/Translation/Translation.js
  packages/web-components/.env.example
Labels: package: services, Ready to merge

#6826 feat(tab-extended-vertical): add "Vertical" Orientation
  packages/styles/scss/components/tabs-extended/_tabs-extended.scss
  packages/web-components/.storybook/container.scss
  packages/web-components/src/components/tabs-extended/__stories__/README.stories.mdx
  packages/web-components/src/components/tabs-extended/__stories__/tabs-extended.stories.ts
  packages/web-components/src/components/tabs-extended/__tests__/tabs-extended.test.ts
  packages/web-components/src/components/tabs-extended/defs.ts
  packages/web-components/src/components/tabs-extended/tabs-extended.ts
  packages/web-components/tests/snapshots/dds-tabs-extended.md
Labels: package: web components, Ready to merge, adopter: AEM

#6915 fix(cloud-masthead-contact-btn): change data-ibm-contact to contact-link
  packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
Labels: adopter: Drupal, feature flag, package: web components, Ready to merge, adopter: Hybrid cloud

#6927 chore(masthead): remove lint warning
  packages/web-components/src/components/masthead/masthead-global-bar.ts
Labels: Ready to merge

#6932 chore(expressive theme): added deprecation note index theme file
  packages/styles/scss/themes/expressive/index.scss
Labels: Ready to merge

#6911 chore(masthead): remove role listitem from navigation items
  packages/web-components/src/components/masthead/masthead-profile.ts
  packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
  packages/web-components/tests/snapshots/dds-masthead-composite.md
Labels: Ready to merge

#6925 fix(video-player): update caption text style
  packages/styles/scss/components/video-player/_video-player.scss
Labels: Ready to merge

#6928 fix(leaving-ibm): token updates
  packages/web-components/src/components/leaving-ibm/leaving-ibm-modal-body.ts
  packages/web-components/src/components/leaving-ibm/leaving-ibm.scss
Labels: Ready to merge

#6938 fix(tabs-extended): adjust scope of vertical tab content spacing rules
  packages/styles/scss/components/tabs-extended/_tabs-extended.scss
Labels: Ready to merge

#6947 fix(cloud-masthead): prevent masthead shifting on top of page
  packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
Labels: feature flag, Ready to merge

#6910 fix(link-list-section): Center align link list items in multi column layouts
  packages/web-components/src/components/card-link/card-link.scss
  packages/web-components/src/components/link-list-section/__stories__/link-list-section.stories.ts
  packages/web-components/src/components/link-list/link-list.scss
  packages/web-components/src/components/link-with-icon/link-with-icon.scss
Labels: package: web components, Ready to merge, adopter: AEM

#6967 fix(footer): Remove role=complimentary from footer legal-nav
  packages/web-components/src/components/footer/legal-nav.ts
  packages/web-components/tests/snapshots/dds-footer-composite.md
Labels: Ready to merge

#6964 fix(footer): Set dds-footer role to contentinfo
  packages/web-components/src/components/footer/footer.ts
  packages/web-components/tests/snapshots/dds-footer-composite.md
Labels: Ready to merge

#6962 fix(cloud-masthead-6956): Safari text showing issue on cloud-top-nav-name
  packages/web-components/src/components/masthead/cloud/cloud-masthead.scss
Labels: feature flag, package: web components, Ready to merge, adopter: Hybrid cloud, owner: Hybrid Cloud

#6999 chore(support): updating support roster for sprint 18
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/contribution_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: dev, Ready to merge

#7005 chore(codesandbox): update leadspace image
  packages/web-components/examples/codesandbox/components/leadspace/assets/images/leadspace-sample-1.jpg
  packages/web-components/examples/codesandbox/components/leadspace/index.html
Labels: package: web components, Ready to merge

#7004 fix(leadspace): update styles so nav and heading are not inline
  packages/styles/scss/components/leadspace/_leadspace.scss
Labels: Ready to merge

#7019 fix(tabs-extended): add word break
  packages/styles/scss/components/tabs-extended/_tabs-extended.scss
Labels: Ready to merge

#7024 fix(cloud-masthead): set unique id for megamenu tabs instead of using title
  packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
Labels: feature flag, package: web components, Ready to merge

#7021 chore(code-scan): introduce codeQL scan workflow
  .github/workflows/codeql-analysis.yml
Labels: dev, Ready to merge
