Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2021-10, with the labels that each got.

#7298 fix(webpack): adding splitchunk optimization for react storybook and upgrade terser plugin
  .yarn/offline-mirror/@gar-promisify-1.1.2.tgz
  .yarn/offline-mirror/@npmcli-fs-1.0.0.tgz
  .yarn/offline-mirror/@npmcli-move-file-1.1.2.tgz
  .yarn/offline-mirror/cacache-15.3.0.tgz
  .yarn/offline-mirror/enhanced-resolve-4.5.0.tgz
  .yarn/offline-mirror/file-loader-6.2.0.tgz
  .yarn/offline-mirror/jest-worker-25.2.6.tgz
  .yarn/offline-mirror/jest-worker-26.6.2.tgz
  .yarn/offline-mirror/mime-db-1.49.0.tgz
  .yarn/offline-mirror/mime-types-2.1.32.tgz
  .yarn/offline-mirror/p-limit-3.1.0.tgz
  .yarn/offline-mirror/schema-utils-2.6.5.tgz
  .yarn/offline-mirror/serialize-javascript-3.1.0.tgz
  .yarn/offline-mirror/serialize-javascript-5.0.1.tgz
  .yarn/offline-mirror/source-map-support-0.5.20.tgz
  .yarn/offline-mirror/ssri-8.0.1.tgz
  .yarn/offline-mirror/terser-4.6.11.tgz
  .yarn/offline-mirror/terser-5.9.0.tgz
  .yarn/offline-mirror/terser-webpack-plugin-1.4.4.tgz
  .yarn/offline-mirror/terser-webpack-plugin-2.3.5.tgz
  .yarn/offline-mirror/terser-webpack-plugin-4.2.3.tgz
  .yarn/offline-mirror/url-loader-4.1.1.tgz
  .yarn/offline-mirror/watchpack-1.7.5.tgz
  .yarn/offline-mirror/watchpack-chokidar2-2.0.1.tgz
  .yarn/offline-mirror/webpack-4.46.0.tgz
  .yarn/offline-mirror/yocto-queue-0.1.0.tgz
  packages/react/.storybook/webpack.config.js
  packages/react/package.json
  packages/web-components/package.json
  yarn.lock
Labels: dev

#7303 chore(ci-check): reducing yarn build scope for faster checks
  .github/workflows/ci-check.yml
Labels: dev, Ready to merge

#7292 fix(cta-section): use sans-serif font for statistics
  packages/web-components/src/components/cta-block/cta-block.scss
Labels: Ready to merge

#7261 feat(data-transpose): data attribute transpositions
  packages/web-components/src/components/table-of-contents/__stories__/wrapper-content.tsx
  packages/web-components/src/components/video-player/video-player-container.ts
  packages/web-components/src/globals/mixins/stable-selector.ts
Labels: Ready to merge

#7307 test(cypress): bumping timeout configuration for web components e2e
  packages/web-components/tests/e2e-storybook/cypress.json
Labels: dev, Ready to merge, hacktoberfest-accepted

#7302 fix(locale-modal-composite): set region item as invalid if locale not configured
  packages/web-components/.storybook/preview-head.html
  packages/web-components/src/components/locale-modal/locale-modal-composite.ts
Labels: package: web components, Ready to merge, hacktoberfest-accepted

#7308 docs(storybook): remove EU locales
  packages/web-components/.storybook/preview-head.html
Labels: Ready to merge, hacktoberfest-accepted

#7285 (masthead): Resolve a11y issues identified by storybook in web components
  packages/web-components/src/components/masthead/left-nav-name.ts
  packages/web-components/src/components/masthead/masthead-profile.ts
  packages/web-components/src/components/masthead/masthead.ts
  packages/web-components/src/components/masthead/top-nav.ts
  packages/web-components/tests/snapshots/dds-masthead-profile.md
Labels: Ready to merge, hacktoberfest-accepted

#7311 chore(issue-template): introduce test scenario creation form
  .github/ISSUE_TEMPLATE/test_scenario_creation.yaml
Labels: dev, Ready to merge, hacktoberfest-accepted

#7306 feat(services): translation and locale to handle `lc` only locales
  packages/react/.storybook/preview-head.html
  packages/services/src/services/Locale/Locale.js
  packages/services/src/services/Locale/__tests__/Locale.test.js
  packages/services/src/services/SearchTypeahead/SearchTypeahead.js
  packages/services/src/services/SearchTypeahead/__tests__/SearchTypeahead.test.js
  packages/services/src/services/Translation/Translation.js
  packages/web-components/.storybook/preview-head.html
Labels: package: services, feature flag, Ready to merge, hacktoberfest-accepted

#7305 feat(data-transpose): changes in light reflect to shadow dom
  packages/web-components/src/globals/mixins/stable-selector.ts
  packages/web-components/tests/snapshots/dds-content-block-card-static.md
Labels: Ready to merge, hacktoberfest-accepted

#7284 fix(masthead): Improve masthead accessibility by removing menu-type roles.
  packages/styles/scss/components/masthead/_masthead-l1.scss
  packages/styles/scss/components/masthead/_masthead-leftnav.scss
  packages/styles/scss/components/masthead/_masthead-megamenu.scss
  packages/styles/scss/components/masthead/_masthead.scss
  packages/web-components/src/components/masthead/cloud/cloud-masthead-profile.ts
  packages/web-components/src/components/masthead/left-nav-menu-item.ts
  packages/web-components/src/components/masthead/left-nav-menu-section.ts
  packages/web-components/src/components/masthead/masthead-profile-item.ts
  packages/web-components/src/components/masthead/masthead-profile.ts
  packages/web-components/src/components/masthead/masthead.scss
  packages/web-components/src/components/masthead/top-nav-item.ts
  packages/web-components/src/components/masthead/top-nav-menu-item.ts
  packages/web-components/src/components/masthead/top-nav-menu.ts
  packages/web-components/src/components/masthead/top-nav.ts
  packages/web-components/tests/snapshots/dds-masthead-composite.md
  packages/web-components/tests/snapshots/dds-masthead-profile.md
Labels: Ready to merge, hacktoberfest-accepted

#7260 feat(print-styles): adding print styles to components
  packages/styles/scss/components/back-to-top/_back-to-top.scss
  packages/styles/scss/components/footer/_footer.scss
  packages/styles/scss/components/masthead/_masthead.scss
  packages/styles/scss/components/tableofcontents/_tableofcontents.scss
  packages/styles/scss/components/tabs-extended/_tabs-extended.scss
  packages/web-components/src/components/table-of-contents/table-of-contents.ts
Labels: Ready to merge

#7289 fix(link-list): update heading font size for video card
  packages/styles/scss/components/link-list/_link-list.scss
  packages/styles/scss/components/link-with-icon/_link-with-icon.scss
  packages/web-components/src/components/link-list/__stories__/link-list.stories.ts
Labels: package: web components, Ready to merge, hacktoberfest-accepted

#7543 fix(browserstack): update cypress configs for browserstack
  packages/react/tests/e2e-storybook/cypress-canary.json
  packages/react/tests/e2e-storybook/cypress-staging.json
  packages/web-components/tests/e2e-storybook/cypress-canary.json
  packages/web-components/tests/e2e-storybook/cypress-staging.json
Labels: dev, Ready to merge

#7527 test(footer): add e2e tests for footer short language only
  packages/react/tests/e2e-storybook/cypress/integration/Footer/Footer.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer.e2e.js
Labels: package: react, package: web components, Ready to merge, test: e2e
