Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2022-11, with the labels that each got.

#9597 fix(storybook): react wrapper props not rendering
  packages/web-components/.storybook/react/main.js
  packages/web-components/src/components/button-group/__stories__/README.stories.react.mdx
  packages/web-components/src/components/dotcom-shell/__stories__/README.stories.react.mdx
  packages/web-components/tools/babel-plugin-create-react-custom-element-type.js
Labels: Ready to merge

#9618 Revert "fix(storybook): react wrapper props not rendering"
  packages/web-components/.storybook/react/main.js
  packages/web-components/src/components/button-group/__stories__/README.stories.react.mdx
  packages/web-components/src/components/dotcom-shell/__stories__/README.stories.react.mdx
  packages/web-components/tools/babel-plugin-create-react-custom-element-type.js
Labels: Ready to merge

#9601 fix(filter-panel): do not rewrite panel header on filter select
  packages/web-components/src/components/filter-panel/filter-panel-composite.ts
Labels: package: web components, Ready to merge

#9617 chore(search): allow option to stop redirection with enter
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
Labels: package: web components, Ready to merge

#9605 fix(masthead): avoid inline styles for CSP compliance
  packages/styles/scss/components/masthead/_masthead.scss
  packages/web-components/src/components/masthead/__tests__/top-nav.test.ts
  packages/web-components/src/components/masthead/top-nav.ts
  packages/web-components/src/globals/mixins/csp-compliance.ts
Labels: RTL, package: web components, Ready to merge, hacktoberfest-accepted

#9635 fix(percy): update storybook config
  packages/web-components/.storybook/main.js
Labels: Ready to merge

#9638 fix(videoplayer analytics): extended custom metrics data detection
  packages/services/src/services/Analytics/Analytics.js
Labels: Ready to merge

#9661 chore(upgrade): upgrade to Carbon 10.58.5
  .yarn/offline-mirror/@carbon-pictograms-react-11.33.0.tgz
  .yarn/offline-mirror/@carbon-pictograms-react-11.34.0.tgz
  .yarn/offline-mirror/carbon-components-react-7.59.4.tgz
  .yarn/offline-mirror/carbon-components-react-7.59.5.tgz
  packages/react/package.json
  packages/styles/package.json
  yarn.lock
Labels: Ready to merge, dependencies

#9660 chore(deps): bump loader-utils from 1.4.0 to 1.4.2
  .yarn/offline-mirror/loader-utils-1.4.0.tgz
  .yarn/offline-mirror/loader-utils-1.4.2.tgz
  yarn.lock
Labels: Ready to merge, dependencies

#9608 fix(table-of-contents): fix subtree observer callback
  packages/web-components/src/components/table-of-contents/table-of-contents.ts
Labels: severity 2, package: web components, Ready to merge, adopter: AEM, owner: AEM, type: bug 🐛

#9311 feat(cta): add email, schedule, chat, call types
  packages/web-components/examples/codesandbox/components/cta-button/contact-methods.html
  packages/web-components/src/component-mixins/cta/cta.ts
  packages/web-components/src/components/cta/__stories__/README.stories.mdx
  packages/web-components/src/components/cta/__stories__/ctaTypeConfig.js
  packages/web-components/src/components/cta/defs.ts
Labels: package: web components, Ready to merge, owner: Innovation Team, test: e2e

#9632 fix(search): fired input event upon clicking suggestion
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
Labels: package: web components, Ready to merge

#9659 feat(search): reintroduce scoped search
  packages/styles/scss/components/search-with-typeahead/_search-with-typeahead.scss
  packages/utilities/src/utilities/settings/settings.js
  packages/web-components/src/components/masthead/__stories__/README.stories.mdx
  packages/web-components/src/components/masthead/__stories__/README.stories.react.mdx
  packages/web-components/src/components/masthead/__stories__/masthead.stories.react.tsx
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/search-with-typeahead/scoped-search-dropdown-mobile.ts
  packages/web-components/src/components/search-with-typeahead/scoped-search-dropdown.ts
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-scoped-search.e2e.js
Labels: package: web components, Ready to merge

#9676 Fix/mobile masthead csp
  packages/carbon-web-components/.storybook/addon-carbon-theme/components/Panel.tsx
  packages/carbon-web-components/.storybook/addon-carbon-theme/register.tsx
  packages/carbon-web-components/src/components/progress-indicator/progress-indicator-skeleton.ts
  packages/carbon-web-components/src/components/structured-list/structured-list-header-cell-skeleton.ts
  packages/carbon-web-components/src/components/tabs/tab-skeleton.ts
  packages/carbon-web-components/src/components/tooltip/tooltip-footer.ts
  packages/carbon-web-components/src/typings/vendor.d.ts
  packages/carbon-web-components/tests/integration/ui/accordion_steps.js
  packages/carbon-web-components/tests/spec/overflow-menu_spec.ts
  packages/utilities/src/utilities/settings/settings.js
  packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
  packages/web-components/src/components/masthead/left-nav-menu-section.ts
  packages/web-components/src/components/masthead/left-nav.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/components/masthead/masthead.ts
  packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
  packages/web-components/src/components/masthead/top-nav.ts
  packages/web-components/src/globals/mixins/csp-compliance.ts
Labels: Ready to merge

#9699 chore(cypress): downgrade to 8.7.0
  .yarn/offline-mirror/@types-sinonjs__fake-timers-6.0.4.tgz
  .yarn/offline-mirror/cypress-8.7.0.tgz
  .yarn/offline-mirror/ramda-0.27.2.tgz
  packages/web-components/package.json
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-custom-search.e2e.js
  yarn.lock
Labels: Ready to merge
