Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2022-09, with the labels that each got.

#9312 feat(masthead-v2): consolidate Cloud auth methods with profileAPI & update docs
  packages/services-store/src/actions/__tests__/profileAPI.test.ts
  packages/services-store/src/actions/profileAPI.ts
  packages/services-store/src/types/profileAPI.ts
  packages/services/src/services/Profile/Profile.js
  packages/web-components/src/components/masthead/__stories__/README.stories.mdx
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
Labels: QA, package: web components, Ready to merge, adopter: Innovation Team

#9322 feat(lightbox-media-viewer): add react wrapper
  packages/web-components/examples/codesandbox/components-react/lightbox-media-viewer/.gitignore
  packages/web-components/examples/codesandbox/components-react/lightbox-media-viewer/index.html
  packages/web-components/examples/codesandbox/components-react/lightbox-media-viewer/package.json
  packages/web-components/examples/codesandbox/components-react/lightbox-media-viewer/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/lightbox-media-viewer/src/index.css
  packages/web-components/examples/codesandbox/components-react/lightbox-media-viewer/src/index.js
  packages/web-components/examples/codesandbox/components-react/lightbox-media-viewer/webpack.config.js
  packages/web-components/src/components/lightbox-media-viewer/__stories__/README.stories.react.mdx
  packages/web-components/src/components/lightbox-media-viewer/__stories__/lightbox-media-viewer.stories.react.tsx
  packages/web-components/src/components/lightbox-media-viewer/lightbox-image-viewer.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-media-viewer-body.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-media-viewer.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player.ts
Labels: Ready to merge

#9318 feat(locale-modal): create React Wrapper
  packages/web-components/.storybook/react/preview-head.html
  packages/web-components/examples/codesandbox/components-react/locale-modal/.gitignore
  packages/web-components/examples/codesandbox/components-react/locale-modal/index.html
  packages/web-components/examples/codesandbox/components-react/locale-modal/package.json
  packages/web-components/examples/codesandbox/components-react/locale-modal/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/locale-modal/src/index.css
  packages/web-components/examples/codesandbox/components-react/locale-modal/src/index.js
  packages/web-components/examples/codesandbox/components-react/locale-modal/webpack.config.js
  packages/web-components/src/components/locale-modal/__stories__/README.stories.react.mdx
  packages/web-components/src/components/locale-modal/__stories__/locale-modal.stories.react.tsx
  packages/web-components/src/components/locale-modal/locale-modal-composite.ts
  packages/web-components/src/components/locale-modal/locale-modal-container.ts
Labels: package: web components, Ready to merge

#9332 fix(actions): fixes gh publish actions with `no-verify` for 2fa
  .github/workflows/publish-alpha.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-nightly.yml
Labels: Ready to merge

#9324 fix(masthead-v2): QA design feedback updates
  packages/styles/scss/components/masthead/_masthead-leftnav.scss
  packages/styles/scss/components/masthead/_masthead-megamenu.scss
  packages/styles/scss/components/masthead/_masthead.scss
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/masthead/masthead.scss
  packages/web-components/src/components/masthead/megamenu-category-group.ts
  packages/web-components/src/components/masthead/megamenu-category-link.ts
Labels: feature flag, package: web components, Ready to merge

#9335 feat(link-list): add react wrapper story
  packages/web-components/examples/codesandbox/components-react/link-list/.gitignore
  packages/web-components/examples/codesandbox/components-react/link-list/index.html
  packages/web-components/examples/codesandbox/components-react/link-list/package.json
  packages/web-components/examples/codesandbox/components-react/link-list/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/link-list/src/index.css
  packages/web-components/examples/codesandbox/components-react/link-list/src/index.js
  packages/web-components/examples/codesandbox/components-react/link-list/webpack.config.js
  packages/web-components/src/components/link-list/__stories__/README.stories.react.mdx
  packages/web-components/src/components/link-list/__stories__/link-list.stories.react.tsx
Labels: package: web components, Ready to merge, :eyes: eyes needed

#9336 feat(search-with-typeahead): update react wrapper
  packages/web-components/src/components/search-with-typeahead/__stories__/search-with-typeahead.stories.react.tsx
  packages/web-components/src/components/search-with-typeahead/scoped-search-dropdown-mobile.ts
  packages/web-components/src/components/search-with-typeahead/scoped-search-dropdown.ts
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead-item.ts
Labels: Ready to merge

#9339 feat(link-list-section): create react wrapper story
  packages/web-components/examples/codesandbox/components-react/link-list-section/.gitignore
  packages/web-components/examples/codesandbox/components-react/link-list-section/index.html
  packages/web-components/examples/codesandbox/components-react/link-list-section/package.json
  packages/web-components/examples/codesandbox/components-react/link-list-section/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/link-list-section/src/index.css
  packages/web-components/examples/codesandbox/components-react/link-list-section/src/index.js
  packages/web-components/examples/codesandbox/components-react/link-list-section/webpack.config.js
  packages/web-components/src/components/link-list-section/__stories__/README.stories.react.mdx
  packages/web-components/src/components/link-list-section/__stories__/link-list-section.stories.react.tsx
Labels: package: web components, Ready to merge

#9331 feat(content-block-cards): react wrapper
  packages/web-components/examples/codesandbox/components-react/content-block-cards/.gitignore
  packages/web-components/examples/codesandbox/components-react/content-block-cards/index.html
  packages/web-components/examples/codesandbox/components-react/content-block-cards/package.json
  packages/web-components/examples/codesandbox/components-react/content-block-cards/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/content-block-cards/src/index.css
  packages/web-components/examples/codesandbox/components-react/content-block-cards/src/index.js
  packages/web-components/examples/codesandbox/components-react/content-block-cards/webpack.config.js
  packages/web-components/src/components/content-block-cards/__stories__/README.stories.react.mdx
  packages/web-components/src/components/content-block-cards/__stories__/content-block-cards.stories.react.tsx
Labels: Ready to merge

#9340 chore(actions): fix `publish-nightly` npm token setting
  .github/workflows/publish-nightly.yml
Labels: Ready to merge

#9342 fix(masthead-butotn-cta): change base class to BXButton
  packages/web-components/src/components/masthead/masthead-button-cta.ts
Labels: package: web components, Ready to merge, owner: Innovation Team, test: CDN preview

#9328 Notice & choice - Refactor and update documentation
  packages/react/examples/codesandbox/components/NoticeChoice/.gitignore
  packages/react/examples/codesandbox/components/NoticeChoice/.sassrc
  packages/react/examples/codesandbox/components/NoticeChoice/package.json
  packages/react/examples/codesandbox/components/NoticeChoice/src/index.js
  packages/react/examples/codesandbox/components/NoticeChoice/src/styles.scss
  packages/react/examples/codesandbox/components/NoticeChoice/webpack.config.js
  packages/react/src/components/NoticeChoice/NoticeChoice.js
  packages/react/src/components/NoticeChoice/README.stories.mdx
Labels: Ready to merge

#9352 feat(dotcom-shell): create react wrapper
  packages/web-components/examples/codesandbox/components-react/dotcom-shell/.gitignore
  packages/web-components/examples/codesandbox/components-react/dotcom-shell/index.html
  packages/web-components/examples/codesandbox/components-react/dotcom-shell/package.json
  packages/web-components/examples/codesandbox/components-react/dotcom-shell/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/dotcom-shell/src/index.css
  packages/web-components/examples/codesandbox/components-react/dotcom-shell/src/index.js
  packages/web-components/examples/codesandbox/components-react/dotcom-shell/webpack.config.js
  packages/web-components/src/components/dotcom-shell/__stories__/README.stories.mdx
  packages/web-components/src/components/dotcom-shell/__stories__/README.stories.react.mdx
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.react.tsx
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
  packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.react.tsx
Labels: Ready to merge

#9367 fix(StickyHeader): fix masthead-l1 logic for Masthead v2
  packages/web-components/src/components/masthead/masthead.ts
Labels: package: web components, Ready to merge, adopter: AEM, owner: Innovation Team

#9359 fix(masthead-v2): fix masthead-contact & add DDO for testing
  packages/web-components/examples/codesandbox/components/masthead/cdn-rtl.html
  packages/web-components/examples/codesandbox/components/masthead/cdn.html
  packages/web-components/examples/codesandbox/components/masthead/index.html
  packages/web-components/examples/codesandbox/components/masthead/package.json
  packages/web-components/examples/codesandbox/components/masthead/src/ddo.js
  packages/web-components/examples/codesandbox/components/masthead/src/index-cdn.js
  packages/web-components/examples/codesandbox/components/masthead/src/index.js
  packages/web-components/examples/codesandbox/components/masthead/src/index.scss
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/components/masthead/masthead-contact.ts
  packages/web-components/tests/snapshots/dds-masthead-composite.md
Labels: package: web components, Ready to merge, owner: Innovation Team, test: e2e, :eyes: eyes needed

#9371 fix(masthead-v2): prevent href-less category heading links
  packages/web-components/src/components/masthead/masthead.scss
  packages/web-components/src/components/masthead/megamenu-category-heading.ts
Labels: package: web components, Ready to merge

#9363 feat(layout): add react wrapper story
  packages/web-components/src/components/layout/__stories__/README.stories.react.mdx
  packages/web-components/src/components/layout/__stories__/layout.stories.react.tsx
Labels: documentation, Ready to merge, storybook

#9402 chore(cwc): add automerge git actions job
  .github/workflows/automerge-import-cwc-repo.yml
Labels: Ready to merge

#9395 docs(content-group-pictograms): add react wrapper story
  packages/web-components/examples/codesandbox/components-react/content-group-pictograms/.gitignore
  packages/web-components/examples/codesandbox/components-react/content-group-pictograms/index.html
  packages/web-components/examples/codesandbox/components-react/content-group-pictograms/package.json
  packages/web-components/examples/codesandbox/components-react/content-group-pictograms/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/content-group-pictograms/src/index.css
  packages/web-components/examples/codesandbox/components-react/content-group-pictograms/src/index.js
  packages/web-components/examples/codesandbox/components-react/content-group-pictograms/webpack.config.js
  packages/web-components/src/components/content-group-pictograms/__stories__/README.stories.react.mdx
  packages/web-components/src/components/content-group-pictograms/__stories__/content-group-pictograms.stories.react.tsx
Labels: documentation, Ready to merge

#9380 fix(notice-choice): missing build script for tests
  packages/react/examples/codesandbox/components/NoticeChoice/package.json
Labels: Ready to merge

#9399 chore(deps): remove duplicate deps
  .yarn/offline-mirror/@types-resolve-0.0.8.tgz
  .yarn/offline-mirror/rollup-plugin-babel-4.4.0.tgz
  .yarn/offline-mirror/rollup-plugin-commonjs-9.3.4.tgz
  .yarn/offline-mirror/rollup-plugin-json-4.0.0.tgz
  .yarn/offline-mirror/rollup-plugin-node-resolve-4.2.4.tgz
  .yarn/offline-mirror/rollup-plugin-replace-2.2.0.tgz
  packages/web-components/package.json
  yarn.lock
Labels: package: web components, Ready to merge

#9400 docs(content-group-simple): add react wrapper story
  packages/web-components/examples/codesandbox/components-react/content-group-simple/.gitignore
  packages/web-components/examples/codesandbox/components-react/content-group-simple/index.html
  packages/web-components/examples/codesandbox/components-react/content-group-simple/package.json
  packages/web-components/examples/codesandbox/components-react/content-group-simple/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/content-group-simple/src/index.css
  packages/web-components/examples/codesandbox/components-react/content-group-simple/src/index.js
  packages/web-components/examples/codesandbox/components-react/content-group-simple/webpack.config.js
  packages/web-components/src/components/content-group-simple/__stories__/README.stories.react.mdx
  packages/web-components/src/components/content-group-simple/__stories__/content-group-simple.stories.react.tsx
  packages/web-components/src/components/content-group-simple/__stories__/data/ContentGroupSimple.knobs.js
Labels: documentation, Ready to merge

#9372 fix(masthead): search locale fix
  packages/react/src/components/Masthead/Masthead.js
  packages/react/src/components/Masthead/MastheadSearch.js
Labels: package: react, Ready to merge

#9379 docs(content-group-cards): add react wrapper story
  packages/web-components/examples/codesandbox/components-react/content-group-cards/.gitignore
  packages/web-components/examples/codesandbox/components-react/content-group-cards/index.html
  packages/web-components/examples/codesandbox/components-react/content-group-cards/package.json
  packages/web-components/examples/codesandbox/components-react/content-group-cards/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/content-group-cards/src/index.css
  packages/web-components/examples/codesandbox/components-react/content-group-cards/src/index.js
  packages/web-components/examples/codesandbox/components-react/content-group-cards/webpack.config.js
  packages/web-components/src/components/content-group-cards/__stories__/README.stories.react.mdx
  packages/web-components/src/components/content-group-cards/__stories__/content-group-cards.stories.react.tsx
  packages/web-components/src/components/content-group-cards/__stories__/content-group-cards.stories.ts
Labels: Ready to merge

#9368 fix(masthead-v2): Optional CTA QA feedback
  packages/web-components/src/components/masthead/left-nav-cta-item.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/components/masthead/masthead.scss
Labels: package: web components, Ready to merge

#9405 fix(link-list): ensure icon stays on top
  packages/styles/scss/components/link-list/_link-list.scss
Labels: Ready to merge

#9407 chore(leadspace-search): add subheading knob
  packages/web-components/src/components/leadspace-with-search/__stories__/leadspace-with-search.stories.ts
Labels: Ready to merge

#9418 fix(scoped-search): experimental storybook6
  packages/web-components/.storybook/manager.js
  packages/web-components/src/components/masthead/__stories__/scoped-search-masthead.stories.ts
Labels: Ready to merge

#9408 feat(cta-block): react wrapper
  packages/web-components/examples/codesandbox/components-react/cta-block/.gitignore
  packages/web-components/examples/codesandbox/components-react/cta-block/index.html
  packages/web-components/examples/codesandbox/components-react/cta-block/package.json
  packages/web-components/examples/codesandbox/components-react/cta-block/sandbox.config.json
  packages/web-components/examples/codesandbox/components-react/cta-block/src/index.css
  packages/web-components/examples/codesandbox/components-react/cta-block/src/index.js
  packages/web-components/examples/codesandbox/components-react/cta-block/webpack.config.js
  packages/web-components/src/components/cta-block/__stories__/README.stories.react.mdx
  packages/web-components/src/components/cta-block/__stories__/cta-block.stories.react.tsx
  packages/web-components/src/components/cta-block/__stories__/cta-block.stories.ts
Labels: Ready to merge

#9426 fix(storybook): dotcomshell/lightbox missing imports
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
  packages/web-components/src/components/lightbox-media-viewer/__stories__/lightbox-media-viewer.stories.ts
Labels: package: web components, Ready to merge, storybook

#9435 fix(filter-panel-input-select): aria expanded
  packages/web-components/src/components/filter-panel/filter-panel-input-select.ts
Labels: accessibility, package: web components, Ready to merge
