Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2024-05, with the labels that each got.

#11745 fix(breadcrumb): add overflow-menu-import
  packages/carbon-web-components/src/components/breadcrumb/index.ts
Labels: Ready to merge, feature flag: cwc, test: CWC CDN preview

#11743 fix(data-table): center align checkboxes
  packages/carbon-web-components/src/components/data-table/_table-core.scss
Labels: Ready to merge, package: carbon web components

#11760 fix(card-group): support RTL borders & padding
  packages/styles/scss/components/card-group/_card-group.scss
  packages/web-components/src/components/card-group/card-group.scss
  packages/web-components/src/components/card-group/card-group.ts
Labels: package: styles, RTL, package: web components, Ready to merge, owner: Innovation Team, Needs design approval, :eyes: eyes needed

#11734 fix(masthead): ensure opened L1 mobile dropdown is visible while there is also a ToC
  packages/styles/scss/components/masthead/_masthead-l1.scss
  packages/utilities/src/utilities/StickyHeader/StickyHeader.js
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
  packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
  packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
  packages/web-components/src/components/masthead/masthead-l1.ts
Labels: package: utilities, package: styles, Ready to merge, adopter: AEM, owner: Innovation Team, test: CDN preview, Masthead L0/L1 v2

#11698 fix(content-group): cta spacing
  packages/styles/scss/internal/content-group/_content-group.scss
  packages/styles/scss/internal/content-item/_content-item.scss
  packages/web-components/src/components/content-group/__stories__/content-group.stories.react.tsx
  packages/web-components/src/components/content-group/__stories__/content-group.stories.ts
  packages/web-components/src/components/content-item/content-item.ts
Labels: package: web components

#11748 [v1] feat(rtl-arrow): Fix arrows used for CTA's when in RTL
  packages/web-components/src/component-mixins/cta/cta.ts
  packages/web-components/src/components/button-group/__stories__/button-group.stories.ts
  packages/web-components/src/components/callout-quote/__stories__/callout-quote.stories.ts
  packages/web-components/src/components/card-in-card/__stories__/card-in-card.stories.ts
  packages/web-components/src/components/card-link/__stories__/card-link.stories.ts
  packages/web-components/src/components/card-section-carousel/__stories__/card-section-carousel.stories.ts
  packages/web-components/src/components/card-section-offset/__stories__/card-section-offset.stories.ts
  packages/web-components/src/components/card/__stories__/card.stories.ts
  packages/web-components/src/components/carousel/__stories__/carousel.stories.ts
  packages/web-components/src/components/content-block-card-static/__stories__/content-block-card-static.stories.ts
  packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.ts
  packages/web-components/src/components/content-group-banner/__stories__/content-group-banner.stories.ts
  packages/web-components/src/components/content-group-cards/__stories__/content-group-cards.stories.ts
  packages/web-components/src/components/content-group-pictograms/__stories__/content-group-pictograms.stories.ts
  packages/web-components/src/components/content-section/__stories__/content-section.stories.ts
  packages/web-components/src/components/cta-block/__stories__/cta-block.stories.ts
  packages/web-components/src/components/cta-section/__stories__/cta-section.stories.ts
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
  packages/web-components/src/components/expressive-modal/__stories__/expressive-modal.stories.ts
  packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
  packages/web-components/src/components/leadspace-block/__stories__/leadspace-block.stories.ts
  packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts
  packages/web-components/src/components/link-list-section/__stories__/link-list-section.stories.ts
  packages/web-components/src/components/link-list/__stories__/link-list.stories.ts
  packages/web-components/src/components/link-with-icon/__stories__/link-with-icon.stories.ts
  packages/web-components/src/components/link-with-icon/link-with-icon.ts
  packages/web-components/src/components/logo-grid/__stories__/logo-grid.stories.ts
  packages/web-components/src/components/pictogram-item/__stories__/pictogram-item.stories.ts
  packages/web-components/src/components/quote/__stories__/quote.stories.ts
  packages/web-components/src/components/tabs-extended/__stories__/tabs-extended.stories.ts
  packages/web-components/tests/snapshots/dds-link-with-icon.md
Labels: bug, dev, RTL, Ready to merge, owner: Innovation Team, test: CDN preview, v1

#11736 feat(rtl-arrow): Fix arrows used for CTA's when in RTL
  packages/web-components/src/component-mixins/cta/cta-v1.ts
  packages/web-components/src/component-mixins/cta/cta.ts
  packages/web-components/src/components/button/button.ts
  packages/web-components/src/components/card-section-carousel/__stories__/card-section-carousel.stories.ts
  packages/web-components/src/components/card-section-offset/__stories__/card-section-offset.stories.ts
  packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.ts
  packages/web-components/src/components/content-group-cards/__stories__/content-group-cards.stories.ts
  packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
  packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts
  packages/web-components/src/components/link-list/__stories__/link-list.stories.ts
  packages/web-components/src/components/link-with-icon/link-with-icon.ts
  packages/web-components/src/components/quote/__stories__/quote.stories.ts
  packages/web-components/src/components/tabs-extended-media/__stories__/tabs-extended-media.stories.ts
  packages/web-components/src/components/tabs-extended/__stories__/tabs-extended.stories.ts
Labels: bug, dev, RTL, Ready to merge, owner: Innovation Team, test: CDN preview

#11761 [v1] fix(parent-visibility): decouple tab from parent visibility
  packages/web-components/src/component-mixins/parent-visibility/parent-visibility.ts
  packages/web-components/src/components/tabs-extended/defs.ts
  packages/web-components/src/components/tabs-extended/tab.ts
Labels: bug, severity 3, dev, package: web components, Ready to merge, adopter: AEM, owner: Innovation Team, test: CDN preview, v1

#11766 chore(sticky-heady): port refactor to v1
  packages/utilities/src/utilities/StickyHeader/StickyHeader.js
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
  packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
  packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
Labels: package: utilities, package: web components, Ready to merge, adopter: AEM, owner: Innovation Team, v1

#11738 fix(content-group): adding h-tags to headings
  packages/carbon-web-components/tests/snapshots/bx-checkbox.md
  packages/carbon-web-components/tests/snapshots/bx-pagination.md
  packages/web-components/src/components/content-block-horizontal/content-block-horizontal.scss
  packages/web-components/src/components/content-group/content-group-heading.ts
  packages/web-components/src/components/content-group/content-group.scss
  packages/web-components/src/components/content-item/content-item-heading.ts
  packages/web-components/src/components/content-item/content-item.scss
  packages/web-components/tests/snapshots/dds-content-block-card-static.md
Labels: Needs design approval, test: CDN preview

#11777 feat(cta-block): add CSS shadowpart
  packages/web-components/src/components/content-block/content-block.ts
  packages/web-components/tests/snapshots/dds-callout-with-media.md
  packages/web-components/tests/snapshots/dds-content-block-cards.md
  packages/web-components/tests/snapshots/dds-content-block-headlines.md
  packages/web-components/tests/snapshots/dds-content-block-horizontal.md
  packages/web-components/tests/snapshots/dds-content-block-media.md
  packages/web-components/tests/snapshots/dds-content-block-segmented.md
  packages/web-components/tests/snapshots/dds-content-block-simple.md
  packages/web-components/tests/snapshots/dds-content-group-banner.md
  packages/web-components/tests/snapshots/dds-content-group-cards.md
  packages/web-components/tests/snapshots/dds-content-group-simple.md
  packages/web-components/tests/snapshots/dds-cta-block.md
Labels: Ready to merge

#11787 chore(dependency): bump up utilities version in services package
  packages/services/package.json
  yarn.lock
Labels: v1

#11792 fix(tearsheet): tearsheet styles and codesandbox example
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/.babelrc
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/.gitignore
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/.sassrc
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/cdn.html
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/index.html
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/package.json
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/sandbox.config.json
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/src/index.js
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/src/styles.scss
  packages/carbon-web-components/src/components/tearsheet/tearsheet-story.ts
  packages/carbon-web-components/src/components/tearsheet/tearsheet.scss
  packages/carbon-web-components/src/components/tearsheet/tearsheet.ts
Labels: Ready to merge

#11793 feat(masthead): use more visible box shadow
  packages/styles/scss/components/masthead/_masthead-l1.scss
Labels: package: styles, adopter: AEM, owner: Innovation Team, :eyes: eyes needed, Masthead L0/L1 v2

#11803 chore(masthead-v2): get latest from alpha dev into alpha release
  packages/styles/scss/components/masthead/_masthead-l1.scss
  packages/utilities/src/utilities/StickyHeader/StickyHeader.js
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
  packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
  packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
  packages/web-components/src/components/masthead/masthead-l1.ts
Labels: adopter: AEM, owner: Innovation Team, Masthead L0/L1 v2

#11801 chore(percy): update config and story snapshots
  .github/workflows/percy-update-base.yml
  packages/web-components/src/components/back-to-top/__stories__/back-to-top.stories.ts
  packages/web-components/src/components/background-media/__stories__/background-media.stories.ts
  packages/web-components/src/components/button/__stories__/button.stories.ts
  packages/web-components/src/components/callout-with-media/__stories__/callout-with-media.stories.ts
  packages/web-components/src/components/card-group/__stories__/card-group.stories.ts
  packages/web-components/src/components/card-in-card/__stories__/card-in-card.stories.ts
  packages/web-components/src/components/card-section-offset/__stories__/card-section-offset.stories.ts
  packages/web-components/src/components/card/__stories__/card.stories.ts
  packages/web-components/src/components/carousel/__stories__/carousel.stories.ts
  packages/web-components/src/components/content-block-cards/__stories__/content-block-cards.stories.ts
  packages/web-components/src/components/content-block-horizontal/__stories__/content-block-horizontal.stories.react.tsx
  packages/web-components/src/components/content-block-media/__stories__/content-block-media.stories.ts
  packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.ts
  packages/web-components/src/components/content-block-segmented/__stories__/content-block-segmented.stories.ts
  packages/web-components/src/components/content-block-simple/__stories__/content-block-simple.stories.ts
  packages/web-components/src/components/content-block/__stories__/content-block.stories.ts
  packages/web-components/src/components/content-group-simple/__stories__/content-group-simple.stories.ts
  packages/web-components/src/components/content-item-row/__stories__/content-item-row.stories.ts
  packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
  packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
  packages/web-components/src/components/feature-section/__stories__/feature-section.stories.ts
  packages/web-components/src/components/global-banner/__stories__/global-banner.stories.ts
  packages/web-components/src/components/image/__stories__/image.stories.ts
  packages/web-components/src/components/leadspace-block/__stories__/leadspace-block.stories.ts
  packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts
  packages/web-components/src/components/logo-grid/__stories__/logo-grid.stories.ts
Labels: Ready to merge, storybook, github_actions

#11797 fix(parent-visibility): Make changes for v2
  packages/web-components/src/component-mixins/parent-visibility/parent-visibility.ts
  packages/web-components/src/components/cta-block/__stories__/cta-block.stories.ts
  packages/web-components/src/components/cta-block/cta-block-item-row.ts
  packages/web-components/src/components/cta-block/cta-block.scss
  packages/web-components/src/components/video-player/video-player.ts
Labels: package: web components, Ready to merge, owner: Innovation Team, v2

#11807 feat(carousel): add shadowparts
  packages/web-components/src/components/carousel/carousel.ts
  packages/web-components/tests/snapshots/c4d-carousel.md
Labels: Feature request, adopter: AEM, owner: Innovation Team, shadow parts

#11809 feat(content-block): add shadowparts
  packages/web-components/src/components/content-block/content-block.ts
  packages/web-components/tests/snapshots/c4d-callout-with-media.md
  packages/web-components/tests/snapshots/c4d-content-block-cards.md
  packages/web-components/tests/snapshots/c4d-content-block-headlines.md
  packages/web-components/tests/snapshots/c4d-content-block-horizontal.md
  packages/web-components/tests/snapshots/c4d-content-block-media.md
  packages/web-components/tests/snapshots/c4d-content-block-segmented.md
  packages/web-components/tests/snapshots/c4d-content-block-simple.md
  packages/web-components/tests/snapshots/c4d-content-group-cards.md
  packages/web-components/tests/snapshots/c4d-content-group-simple.md
  packages/web-components/tests/snapshots/c4d-cta-block.md
  packages/web-components/tests/snapshots/c4d-in-page-banner.md
  packages/web-components/tests/snapshots/c4d-logo-grid.md
Labels: Feature request, adopter: AEM, owner: Innovation Team, shadow parts

#11802 feat(card): add shadow parts
  packages/web-components/src/components/card/card.ts
  packages/web-components/tests/snapshots/c4d-card-in-card.md
  packages/web-components/tests/snapshots/c4d-card.md
  packages/web-components/tests/snapshots/c4d-content-group-simple.md
  packages/web-components/tests/snapshots/c4d-feature-card.md
Labels: shadow parts

#11814 feat(content-item): add shadow parts
  packages/web-components/src/components/content-item/content-item.ts
Labels: shadow parts

#11816 feat(content-section): add shadow parts
  packages/web-components/src/components/content-section/content-section.ts
Labels: shadow parts

#11821 fix(side-panel): import missing icon-button and codesandbox example
  packages/carbon-web-components/examples/codesandbox/basic/components/side-panel/cdn.html
  packages/carbon-web-components/examples/codesandbox/basic/components/side-panel/index.html
  packages/carbon-web-components/examples/codesandbox/basic/components/side-panel/package.json
  packages/carbon-web-components/examples/codesandbox/basic/components/side-panel/src/index.js
  packages/carbon-web-components/examples/codesandbox/basic/components/side-panel/src/styles.scss
  packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/cdn.html
  packages/carbon-web-components/src/components/side-panel/side-panel.ts
Labels: Ready to merge

#11827 feat(dotcom-shell): add shadow parts
  packages/web-components/src/components/dotcom-shell/dotcom-shell.ts
Labels: shadow parts

#11817 feat(cta): add shadow parts
  packages/web-components/src/components/cta/card-cta-footer.ts
  packages/web-components/src/components/cta/card-cta.ts
  packages/web-components/src/components/cta/cta.ts
  packages/web-components/src/components/cta/feature-cta.ts
Labels: shadow parts

#11773 chore(sticky-header): port refactor to v2
  packages/styles/scss/components/masthead/_masthead-l1.scss
  packages/utilities/src/utilities/StickyHeader/StickyHeader.js
  packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
  packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
  packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts
  packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
  packages/web-components/src/components/masthead/masthead-l1.ts
Labels: package: utilities, package: styles, package: web components, Ready to merge, owner: Innovation Team, v2

#11833 feat(filter-panel): add shadow parts
  packages/web-components/src/components/filter-panel/filter-panel-composite.ts
  packages/web-components/src/components/filter-panel/filter-panel-input-select-item.ts
  packages/web-components/src/components/filter-panel/filter-panel-input-select.ts
  packages/web-components/src/components/filter-panel/filter-panel-modal.ts
  packages/web-components/src/components/filter-panel/filter-panel.ts
  packages/web-components/tests/snapshots/c4d-filter-panel-composite.md
Labels: shadow parts

#11829 feat(expressive-modal): add shadow parts
  packages/web-components/src/components/expressive-modal/expressive-modal.ts
  packages/web-components/tests/snapshots/c4d-expressive-modal.md
  packages/web-components/tests/snapshots/c4d-locale-modal.md
Labels: shadow parts
