Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2024-10, with the labels that each got.

#12059 fix(masthead): hide scroller buttons when there are no menuItems
  packages/web-components/src/components/masthead/__stories__/links.ts
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/masthead/masthead-l1.ts
Labels: bug, Ready to merge, adopter: AEM, owner: Innovation Team, test: CDN preview, v2

#12063 [card-group]: Refactor to use subgrid in favor of sameHeight
  packages/styles/scss/components/card-group/_card-group.scss
  packages/styles/scss/components/card/_card.scss
  packages/web-components/src/components/card-group/card-group-item.ts
  packages/web-components/src/components/card-group/card-group.ts
  packages/web-components/src/components/card/card.ts
Labels: Feature request, package: web components, Ready to merge, adopter: AEM, owner: Innovation Team, test: CDN preview

#12069 feat(card): fix video cta data
  packages/web-components/src/components/card/card.ts
  packages/web-components/src/components/cta/video-cta-composite.ts
  packages/web-components/src/components/video-player/__stories__/video-player.stories.ts
Labels: package: web components, Ready to merge, adopter: AEM, owner: Innovation Team, test: CDN preview

#12064 fix(legal-nav): fix adjunct links not showing
  packages/web-components/src/components/footer/legal-nav.ts
Labels: bug, severity 2, dev, package: web components, Ready to merge, adopter: AEM, owner: Innovation Team, test: CDN preview

#12068 fix(card): arrow direction on RTL
  packages/web-components/src/components/card/card.ts
Labels: Ready to merge

#12070 feat(video-player): enable autoplay & load as muted
  packages/web-components/src/components/video-player/__stories__/video-player.stories.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player-container.ts
  packages/web-components/src/components/video-player/video-player.ts
Labels: Ready to merge

#12075 chore(telemetry): updated telemetry.yml endpoint
  packages/services/README.md
  packages/services/telemetry.yml
  packages/styles/README.md
  packages/styles/telemetry.yml
  packages/utilities/README.md
  packages/utilities/telemetry.yml
  packages/web-components/README.md
  packages/web-components/telemetry.yml
Labels: Ready to merge

#12076 chore(telemetry): update telemetry.yml endpoint in v1 branch
  packages/carbon-web-components/README.md
  packages/carbon-web-components/telemetry.yml
  packages/react/README.md
  packages/react/telemetry.yml
  packages/services/README.md
  packages/services/telemetry.yml
  packages/styles/README.md
  packages/styles/telemetry.yml
  packages/utilities/README.md
  packages/utilities/telemetry.yml
  packages/web-components/README.md
  packages/web-components/telemetry.yml
Labels: Ready to merge, v1

#12079 Fix for bundling code with references to @carbon/ibmdotcom-services-store
  packages/web-components/gulp-tasks/clean.js
  packages/web-components/gulp-tasks/config.js
  packages/web-components/gulp-tasks/vendor.js
  packages/web-components/src/components/cta/video-cta-composite.ts
  packages/web-components/src/components/cta/video-cta-container.ts
  packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
  packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts
  packages/web-components/src/components/dotcom-shell/dotcom-shell-container.ts
  packages/web-components/src/components/footer/__stories__/adjunct-links.ts
  packages/web-components/src/components/footer/__stories__/legal-links.ts
  packages/web-components/src/components/footer/__stories__/links.ts
  packages/web-components/src/components/footer/__tests__/footer-composite.test.ts
  packages/web-components/src/components/footer/footer-composite.ts
  packages/web-components/src/components/footer/footer-container.ts
  packages/web-components/src/components/leaving-ibm/leaving-ibm-composite.ts
  packages/web-components/src/components/leaving-ibm/leaving-ibm-connect.ts
  packages/web-components/src/components/leaving-ibm/leaving-ibm-container.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-container.ts
  packages/web-components/src/components/locale-modal/__tests__/locale-modal-composite.test.ts
  packages/web-components/src/components/locale-modal/locale-modal-composite.ts
  packages/web-components/src/components/locale-modal/locale-modal-container.ts
  packages/web-components/src/components/masthead/__stories__/links.ts
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/masthead/__stories__/profile-items.ts
  packages/web-components/src/components/masthead/__stories__/scoped-search-masthead.stories.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/components/masthead/masthead-container.ts
  packages/web-components/src/components/masthead/masthead-l1.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player-container.ts
Labels: bug, dev, Ready to merge, adopter: AEM, owner: Innovation Team

#12081 fix(video-player): correct a visual regression with background video in some contexts
  packages/styles/scss/components/video-player/_video-player.scss
  packages/web-components/src/components/background-media/__stories__/README.stories.mdx
  packages/web-components/src/components/background-media/__stories__/background-media.stories.ts
  packages/web-components/src/components/leadspace/__stories__/README.stories.mdx
  packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player-container.ts
Labels: bug, Ready to merge, test: CDN preview, v1

#12083 fix(content-block-simple): update footer spacing
  packages/web-components/src/components/content-block-simple/content-block-simple.scss
Labels: Ready to merge

#12074 fix(conten-group-heading): render h3 tag to light DOM
  packages/styles/scss/internal/content-group/_content-group.scss
  packages/web-components/src/components/content-group/content-group-heading.ts
Labels: Ready to merge, test: CDN preview

#12082 fix(feature-card): fix feature card broken styles and refactor
  packages/styles/scss/components/card/_card.scss
  packages/styles/scss/components/feature-card/_feature-card.scss
  packages/web-components/src/components/card/card.ts
  packages/web-components/src/components/cta/feature-cta.ts
Labels: bug, dev, Ready to merge, v2
