Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2024-11, with the labels that each got.

#12084 fix(cta): prevent an infinate loop of fetching video details
  packages/web-components/src/component-mixins/cta/cta.ts
Labels: Ready to merge, test: CDN preview

#12089 [feature] Add cart icon to Masthead for SAP Commerce integration
  packages/services/src/services/SAPCommerce/SAPCommerce.js
  packages/services/src/services/SAPCommerce/index.js
  packages/services/src/services/index.js
  packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
  packages/web-components/src/components/masthead/masthead-cart.ts
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/components/masthead/masthead.scss
Labels: Feature request, dev, Ready to merge, adopter: AEM, owner: AEM, test: CDN preview

#12097 (card): Remove class form footer to make component clickable
  packages/styles/scss/components/card/_card.scss
  packages/web-components/src/components/card/card.ts
Labels: Ready to merge, test: CDN preview

#12091 feat(tile, tile-group): add components
  packages/web-components/src/components/tile/__stories__/README--tile-group.stories.mdx
  packages/web-components/src/components/tile/__stories__/README--tile.stories.mdx
  packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
  packages/web-components/src/components/tile/__stories__/tile.stories.ts
  packages/web-components/src/components/tile/index.ts
  packages/web-components/src/components/tile/tile-group.ts
  packages/web-components/src/components/tile/tile.scss
  packages/web-components/src/components/tile/tile.ts
  packages/web-components/tests/snapshots/c4d-card-in-card.md
  packages/web-components/tests/snapshots/c4d-card.md
  packages/web-components/tests/snapshots/c4d-content-block-card-static.md
  packages/web-components/tests/snapshots/c4d-feature-card.md
  packages/web-components/tests/snapshots/c4d-masthead-profile.md
Labels: Ready to merge, Needs design approval

#12101 fix(structured-list, pricing-table): correct coloration, spacing & alignment
  packages/styles/scss/components/pricing-table/_pricing-table.scss
  packages/styles/scss/components/structured-list/_structured-list.scss
  packages/web-components/src/components/structured-list/structured-list-cell.ts
Labels: Ready to merge

#12103 refactor(tile): use relative paths for imports in the same pkg
  packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
  packages/web-components/src/components/tile/__stories__/tile.stories.ts
Labels: Ready to merge

#12100 feat(promo-banner): add components
  packages/web-components/src/components/promo-banner/__stories__/README.stories.mdx
  packages/web-components/src/components/promo-banner/__stories__/promo-banner.stories.ts
  packages/web-components/src/components/promo-banner/index.ts
  packages/web-components/src/components/promo-banner/promo-banner.scss
  packages/web-components/src/components/promo-banner/promo-banner.ts
Labels: Ready to merge

#12102 feat(star-rating): new component
  packages/web-components/examples/stackblitz/components/dotcom-shell/src/index.scss
  packages/web-components/examples/stackblitz/components/masthead-l1/src/index.scss
  packages/web-components/examples/stackblitz/components/masthead/src/index.scss
  packages/web-components/examples/stackblitz/components/table-of-contents/src/index.scss
  packages/web-components/examples/stackblitz/components/tabs-extended/src/styles.scss
  packages/web-components/examples/stackblitz/usage/webpack-handlebars/src/index.scss
  packages/web-components/examples/stackblitz/usage/webpack-sass/src/index.scss
  packages/web-components/src/components/star-rating/__stories__/README.stories.mdx
  packages/web-components/src/components/star-rating/__stories__/star-rating.stories.ts
  packages/web-components/src/components/star-rating/index.ts
  packages/web-components/src/components/star-rating/star-rating.scss
  packages/web-components/src/components/star-rating/star-rating.ts
Labels: Ready to merge

#12107 fix(tile): add a knob to have deterministic random in label and headline
  packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
  packages/web-components/src/components/tile/__stories__/tile.stories.ts
Labels: Ready to merge

#12088 fix(megamenu-tab): change default value override method
  packages/web-components/src/components/masthead/megamenu-tab.ts
Labels: Ready to merge

#12106 fix(masthead-l1): set default active item based on host & pathname
  packages/web-components/src/components/masthead/__stories__/links.ts
  packages/web-components/src/components/masthead/masthead-l1.ts
Labels: Ready to merge, test: CDN preview

#12110 fix(build): update package import paths with .js ext
  packages/web-components/src/components/masthead/masthead-cart.ts
  packages/web-components/src/components/structured-list/structured-list-cell.ts
  packages/web-components/src/components/tile/tile-group.ts
  packages/web-components/src/components/tile/tile.ts
Labels: bug, dev, Ready to merge, adopter: AEM, owner: Innovation Team

#12112 fix(locale-search): fix class fields error for inputTimeout
  packages/web-components/src/globals/mixins/throttled-input.ts
Labels: Ready to merge

#12085 [tests] fix e2e-storybook tests
  .github/workflows/e2e-tests-parallel.yml
  packages/web-components/package.json
  packages/web-components/src/components/card/__stories__/card.stories.ts
  packages/web-components/tests/e2e-storybook/cypress.json
  packages/web-components/tests/e2e-storybook/cypress/integration/card-section-simple/card-section-simple.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/card/card.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/carousel/carousel.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/content-group-pictograms/content-group-pictograms.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/content-item/content-item.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/cta-block/cta-block.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/cta/_tests.js
  packages/web-components/tests/e2e-storybook/cypress/integration/cta/button-cta.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/cta/card-link.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/cta/card.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/cta/feature.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/cta/text-cta.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/feature-card/feature-card.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/feature-section/feature-section.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/filter-panel/filter-panel.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer-micro.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer-short.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/leadspace/leadspace.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/lightbox-media-viewer/lightbox-media-viewer.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/link-list/default.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/link-list/end-of-section.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/link-list/horizontal.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/link-list/vertical.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/link-with-icon/default.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/locale-modal/locale-modal.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/logo-grid/logo-grid.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-custom-search.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-default.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-l1.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-scoped-search.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-search-onload.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/pictogram-item/pictogram-item.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/pricing-table/_tests.js
  packages/web-components/tests/e2e-storybook/cypress/integration/pricing-table/default.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/pricing-table/with-subheaders.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/pricing-table/without-row-headers.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/structured-list/structured-list.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/table-of-contents/table-of-contents.e2e.js
Labels: Ready to merge

#12115 fix(tile): avoid deprecated c4d-tag-group
  packages/web-components/src/components/tile/__stories__/tile.stories.ts
Labels: Ready to merge

#12118 fix(toc): alignment issues
  package.json
  packages/styles/scss/components/tableofcontents/_table-of-contents.scss
Labels: Ready to merge

#12117 fix(leadspace): in storybook adding long copy to copy knob led to button being clipped away
  packages/styles/scss/components/leadspace/_leadspace.scss
Labels: Ready to merge

#12123 fix(card): remove onclick handler for pictogram
  packages/web-components/src/components/card/card.ts
Labels: Ready to merge

#12124 fix(callout-with-media): spacing adjustments
  packages/styles/scss/components/callout-with-media/_callout-with-media.scss
Labels: Ready to merge

#12133 fix(toc): tweak media query for sidebar at lg
  packages/web-components/src/components/table-of-contents/table-of-contents.ts
Labels: Ready to merge

#12134 fix(footer): pass along the placeholder text to combo-box
  packages/web-components/src/components/footer/footer-composite.ts
Labels: Ready to merge

#12135 fix(footer): adjustments to style for color and positioning
  packages/styles/scss/components/footer/_footer.scss
  packages/styles/scss/components/footer/_legal-nav.scss
Labels: Ready to merge

#12136 fix(footer): adjustments to adjunct links visibility
  packages/styles/scss/components/footer/_footer.scss
  packages/web-components/src/components/footer/legal-nav.ts
Labels: Ready to merge
