Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2024-12, with the labels that each got.

#12132 chore(ci): remove mastheadv2 jobs now that its fully released on v2
  .github/workflows/automerge-mastheadv2.yml
  .github/workflows/e2e-integration.yml
Labels: Ready to merge

#12130 test(e2e-storybook): fix feature-card e2e skipped tests and make them…
  packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
  packages/web-components/tests/e2e-storybook/cypress/integration/feature-card/feature-card.e2e.js
Labels: Ready to merge

#12139 fix(leadspace-breadcrumb): leadspace breadcrumb was missing a max-width
  packages/styles/scss/components/leadspace/_leadspace.scss
Labels: Ready to merge

#12141 fix(card): remove bad styles
  packages/styles/scss/components/card/_card.scss
Labels: Ready to merge

#12128 fix(card-group): set min height to content
  packages/styles/scss/components/card-group/_card-group.scss
Labels: priority: high, Ready to merge

#12140 fix(cta-block): adjust cta-block-item-row inline margin
  packages/styles/scss/internal/content-block/_content-block.scss
Labels: priority: high, Ready to merge

#12143 fix(button): avoid taking any video name bubbled on the page
  packages/web-components/src/components/button/button.ts
  packages/web-components/tests/e2e-storybook/cypress/integration/button-group/button-group.e2e.js
Labels: priority: high, Ready to merge

#12145 fix(storybook): incorrect use of theme mixin
  packages/web-components/.storybook/container.scss
Labels: priority: low, Ready to merge

#12144 fix(toc): remove implicit top and bottom padding for TOC
  packages/styles/scss/components/tableofcontents/_table-of-contents.scss
  packages/web-components/src/components/table-of-contents/__stories__/table-of-contents.stories.scss
Labels: priority: high, Ready to merge

#12146 fix(feature-card): inverse styles and cta-type="video"
  packages/styles/scss/components/feature-card/_feature-card.scss
  packages/web-components/src/components/card/card.ts
  packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
Labels: priority: high, Ready to merge

#12148 Release catchup
  .github/workflows/automerge-mastheadv2.yml
  .github/workflows/e2e-integration.yml
  packages/styles/scss/components/card-group/_card-group.scss
  packages/styles/scss/components/card/_card.scss
  packages/styles/scss/components/feature-card/_feature-card.scss
  packages/styles/scss/components/leadspace/_leadspace.scss
  packages/styles/scss/components/notice-choice/_notice-choice.scss
  packages/styles/scss/components/tableofcontents/_table-of-contents.scss
  packages/styles/scss/internal/content-block/_content-block.scss
  packages/web-components/.storybook/container.scss
  packages/web-components/src/components/button/button.ts
  packages/web-components/src/components/card/card.ts
  packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
  packages/web-components/src/components/notice-choice/__stories__/README.stories.mdx
  packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts
  packages/web-components/src/components/notice-choice/notice-choice.ts
  packages/web-components/src/components/notice-choice/services.ts
  packages/web-components/src/components/notice-choice/utils.ts
  packages/web-components/src/components/table-of-contents/__stories__/table-of-contents.stories.scss
  packages/web-components/tests/e2e-storybook/cypress/integration/button-group/button-group.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/feature-card/feature-card.e2e.js
Labels: Ready to merge

#12147 fix(notice-choice): switch attribute to snake case
  packages/web-components/src/components/notice-choice/notice-choice.ts
Labels: priority: low, Ready to merge

#12151 fix(button): fix disable state of the button
  packages/web-components/src/components/button/button.ts
Labels: Ready to merge

#12138 Card group item inverse color scheme
  packages/styles/scss/components/card/_card.scss
  packages/web-components/src/components/card-group/__stories__/card-group.stories.ts
Labels: priority: high, Ready to merge

#12150 feat(video-player): enable autoplay & load as muted
  packages/styles/scss/components/video-player/_video-player.scss
  packages/web-components/src/components/background-media/__stories__/README.stories.mdx
  packages/web-components/src/components/background-media/__stories__/background-media.stories.ts
  packages/web-components/src/components/leadspace/__stories__/README.stories.mdx
  packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts
  packages/web-components/src/components/video-player/__stories__/video-player.stories.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player-container.ts
  packages/web-components/src/components/video-player/video-player.ts
Labels: Ready to merge

#12137 fix(card): push the footer to the bottom of the card consistently
  packages/styles/scss/components/card/_card.scss
Labels: priority: high, Ready to merge

#12125 fix(link-list): v2 style regressions
  packages/styles/scss/components/link-list/_link-list.scss
  packages/web-components/src/components/link-list/__stories__/link-list.stories.ts
  packages/web-components/tests/e2e-storybook/cypress/integration/link-list/default.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/link-list/horizontal.e2e.js
  packages/web-components/tests/e2e-storybook/cypress/integration/link-list/vertical.e2e.js
Labels: priority: high

#12152 chore(styles): properly handle to-rem func calls
  packages/styles/scss/components/button-group/_button-group.scss
  packages/styles/scss/components/callout-with-media/_callout-with-media.scss
  packages/styles/scss/components/card-group/_card-group.scss
  packages/styles/scss/components/card-in-card/_card-in-card.scss
  packages/styles/scss/components/card-section-offset/_card-section-offset.scss
  packages/styles/scss/components/content-block-media/_content-block-media.scss
  packages/styles/scss/components/content-block-mixed/_content-block-mixed.scss
  packages/styles/scss/components/content-block-simple/_content-block-simple.scss
  packages/styles/scss/components/content-item-row-media/_content-item-row-media.scss
  packages/styles/scss/components/content-item-row/_content-item-row.scss
  packages/styles/scss/components/cta-block/_cta-block.scss
  packages/styles/scss/components/expressive-modal/_expressive-modal.scss
  packages/styles/scss/components/filter-panel/_filter-panel.scss
  packages/styles/scss/components/footer/_footer.scss
  packages/styles/scss/components/footer/_language-selector.scss
  packages/styles/scss/components/global-banner/_global-banner.scss
  packages/styles/scss/components/image/_image.scss
  packages/styles/scss/components/leadspace-block/_leadspace-block.scss
  packages/styles/scss/components/leadspace-with-search/_leadspace-with-search.scss
  packages/styles/scss/components/leadspace/_leadspace.scss
  packages/styles/scss/components/search-with-typeahead/_search-with-typeahead.scss
  packages/styles/scss/components/tableofcontents/_table-of-contents.scss
  packages/styles/scss/components/tabs-extended/_tabs-extended.scss
  packages/styles/scss/components/tag-link/_tag-link.scss
  packages/styles/scss/globals/utils/_content-width.scss
  packages/styles/scss/patterns/blocks/callout-data/_callout-data.scss
  packages/styles/scss/patterns/blocks/leadspace-block/_leadspace-block.scss
  packages/styles/scss/patterns/sections/leadspace/_leadspace.scss
Labels: priority: medium, Ready to merge

#12155 fix(card): pictogram related style adjustments
  packages/styles/scss/components/card-group/_card-group.scss
  packages/styles/scss/components/card/_card.scss
  packages/web-components/src/components/card-group/__stories__/card-group.stories.ts
Labels: Ready to merge

#12160 fix(content-group-cards): fix alignment
  packages/styles/scss/components/content-group-cards/_content-group-cards.scss
  packages/styles/scss/internal/content-block/_content-block.scss
Labels: Ready to merge

#12158 fix(background-media): avoid potential VPC setup race
  packages/web-components/src/components/background-media/background-media.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
Labels: Ready to merge

#12174 fix(card-group): subgrid fixes
  packages/styles/scss/components/card-group/_card-group.scss
  packages/web-components/src/components/cta-block/cta-block.scss
Labels: priority: high, Ready to merge

#12172 fix(card): allow copy other than <p> tags
  packages/web-components/src/components/card/__stories__/card.stories.ts
  packages/web-components/src/components/card/card.ts
Labels: priority: high, Ready to merge

#12168 fix(video): remove @state declaration for function _embedMedia
  packages/web-components/src/components/cta/video-cta-composite.ts
Labels: priority: high, Ready to merge, test: CDN preview

#12169 fix(cta): cause ctas to only respond to relevant video events
  packages/web-components/src/components/cta/button-cta.ts
  packages/web-components/src/components/cta/cta.ts
Labels: priority: high, test: CDN preview

#12113 feat(video-player): migrate caem-video-player features
  packages/styles/scss/components/content-group-cards/_content-group-cards.scss
  packages/styles/scss/components/video-player/_video-player.scss
  packages/web-components/src/components/card-in-card/__stories__/card-in-card.stories.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts
  packages/web-components/src/components/video-player/__stories__/video-player.stories.ts
  packages/web-components/src/components/video-player/defs.ts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player-container.ts
  packages/web-components/src/components/video-player/video-player.ts
  packages/web-components/src/globals/internal/enum-helpers.ts
Labels: priority: medium, Ready to merge
