Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2024-07, with the labels that each got.

#11901 feat(code-snippet): add shadow parts
  packages/carbon-web-components/src/components/code-snippet/code-snippet-skeleton.ts
  packages/carbon-web-components/src/components/code-snippet/code-snippet.ts
Labels: shadow parts

#11906 feat(chat-button): add shadow parts
  packages/carbon-web-components/src/components/chat-button/chat-button-skeleton.ts
  packages/carbon-web-components/src/components/chat-button/chat-button.ts
Labels: shadow parts

#11905 feat(checkbox): add shadow parts
  packages/carbon-web-components/src/components/checkbox/checkbox-group.ts
  packages/carbon-web-components/src/components/checkbox/checkbox-skeleton.ts
  packages/carbon-web-components/src/components/checkbox/checkbox.ts
Labels: shadow parts

#11904 feat(content-switcher): add shadow parts
  packages/carbon-web-components/src/components/content-switcher/content-switcher-item.ts
Labels: shadow parts

#11911 fix(text-cta): prevent order of operations issues
  packages/web-components/src/component-mixins/cta/video.ts
Labels: bug, Ready to merge, owner: Innovation Team, test: CDN preview, v1

#11881 feat(masthead): adding shadow parts
  packages/web-components/src/components/masthead/left-nav-menu-category-heading.ts
  packages/web-components/src/components/masthead/left-nav-menu-section.ts
  packages/web-components/src/components/masthead/left-nav-menu.ts
  packages/web-components/src/components/masthead/left-nav-name.ts
  packages/web-components/src/components/masthead/masthead-contact.ts
  packages/web-components/src/components/masthead/masthead-global-bar.ts
  packages/web-components/src/components/masthead/masthead-l1-cta.ts
  packages/web-components/src/components/masthead/masthead-l1-name.ts
  packages/web-components/src/components/masthead/masthead-l1.ts
  packages/web-components/src/components/masthead/masthead-menu-button.ts
  packages/web-components/src/components/masthead/masthead-profile.ts
  packages/web-components/src/components/masthead/masthead.ts
  packages/web-components/src/components/masthead/megamenu-category-group.ts
  packages/web-components/src/components/masthead/megamenu-heading.ts
  packages/web-components/src/components/masthead/megamenu-right-navigation.ts
  packages/web-components/src/components/masthead/megamenu-tab.ts
  packages/web-components/src/components/masthead/megamenu.ts
  packages/web-components/src/components/masthead/top-nav-name.ts
  packages/web-components/src/components/masthead/top-nav.ts
  packages/web-components/tests/snapshots/c4d-left-nav-menu.md
  packages/web-components/tests/snapshots/c4d-masthead-profile.md
Labels: shadow parts

#11903 chore(storybook): add ibm-commons analytics tag
  packages/carbon-web-components/.storybook/preview-head.html
  packages/web-components/.storybook/preview-head.html
  packages/web-components/.storybook/react/preview-head.html
Labels: Ready to merge, storybook

#11916 fix(fonts): set font path for plex fonts cdn
  packages/web-components/src/globals/scss/plex.scss
Labels: Ready to merge, test: CDN preview

#11918 fix(package): remove no longer needed wicg-inert package
  .yarn/cache/wicg-inert-npm-3.1.2-786d525c4e-a726f5ca2d.zip
  packages/web-components/package.json
  packages/web-components/src/components/carousel/carousel.ts
  yarn.lock
Labels: Ready to merge

#11919 fix(package): remove unneeded wicg-inert package - v1
  packages/web-components/package.json
  packages/web-components/src/components/carousel/carousel.ts
  yarn.lock
Labels: Ready to merge

#11920 feat(copy): add shadow parts
  packages/carbon-web-components/src/components/copy/copy.ts
Labels: shadow parts

#11922 feat(tag): add shadow parts
  packages/carbon-web-components/src/components/tag/tag.ts
Labels: shadow parts

#11927 feat(tabs): add shadow parts
  packages/carbon-web-components/src/components/tabs/tab-skeleton.ts
  packages/carbon-web-components/src/components/tabs/tab.ts
  packages/carbon-web-components/src/components/tabs/tabs-skeleton.ts
  packages/carbon-web-components/src/components/tabs/tabs.ts
Labels: shadow parts

#11930 feat(pagination): adding shadow parts
  packages/carbon-web-components/src/components/pagination/pagination.ts
  packages/carbon-web-components/tests/snapshots/cds-copy-button.md
Labels: shadow parts

#11929 chore(ibm-common): add mandatory IBM instrumentation tags (v2)
  packages/web-components/.storybook/manager-head.html
  packages/web-components/.storybook/preview-head.html
  packages/web-components/.storybook/react/manager-head.html
  packages/web-components/.storybook/react/preview-head.html
Labels: Ready to merge

#11934 feat(textarea): add shadow parts
  packages/carbon-web-components/src/components/textarea/textarea-skeleton.ts
  packages/carbon-web-components/src/components/textarea/textarea.ts
Labels: shadow parts

#11937 fix(custom-element): ensure all cwc components use carbonElement
  packages/carbon-web-components/src/components/chat-button/chat-button.ts
  packages/carbon-web-components/src/components/copy-button/copy-button.ts
  packages/carbon-web-components/src/components/copy/copy.ts
  packages/carbon-web-components/src/components/data-table/table-skeleton.ts
  packages/carbon-web-components/src/components/file-uploader/demo-file-uploader.ts
  packages/carbon-web-components/src/components/file-uploader/file-uploader-button.ts
  packages/carbon-web-components/src/components/form-group/form-group.ts
  packages/carbon-web-components/src/components/icon-button/icon-button.ts
  packages/carbon-web-components/src/components/layer/layer.ts
  packages/carbon-web-components/src/components/notification/actionable-notification.ts
  packages/carbon-web-components/src/components/popover/popover-content.ts
  packages/carbon-web-components/src/components/popover/popover.ts
  packages/carbon-web-components/src/components/progress-bar/progress-bar.ts
  packages/carbon-web-components/src/components/select/select-skeleton.ts
  packages/carbon-web-components/src/components/stack/stack.ts
  packages/carbon-web-components/src/components/text-input/text-input-skeleton.ts
  packages/carbon-web-components/src/components/text-input/text-input.ts
  packages/carbon-web-components/src/components/toggle-tip/toggletip.ts
  packages/carbon-web-components/src/components/ui-shell/header-global-action.ts
  packages/carbon-web-components/src/components/ui-shell/header-panel.ts
  packages/carbon-web-components/src/components/ui-shell/header-side-nav-items.ts
  packages/carbon-web-components/src/components/ui-shell/switcher-item.ts
  packages/carbon-web-components/src/components/ui-shell/switcher.ts
Labels: Ready to merge

#11941 chore(deps): set react package to private
  packages/react/package.json
Labels: package: react, Ready to merge, dependencies

#11935 feat(toggle): add shadow parts
  packages/carbon-web-components/src/components/toggle/toggle.ts
Labels: shadow parts

#11939 feat(toggle-tip): add shadow parts
  packages/carbon-web-components/src/components/toggle-tip/toggletip.ts
Labels: shadow parts

#11938 feat(text-input): adding shadow parts
  packages/carbon-web-components/src/components/text-input/text-input-skeleton.ts
  packages/carbon-web-components/src/components/text-input/text-input.ts
Labels: shadow parts

#11943 fix(build): fix exports subpaths
  packages/web-components/package.json
Labels: bug, dev, v2

#11942 fix(build): fix exports subpaths
  packages/react/package.json
  packages/web-components/package.json
Labels: bug, dev, v1

#11947 chore(dependency): update carbon-components-react version to remove wicg-inert security alert
  .yarn/cache/@carbon-feature-flags-npm-0.7.0-7f192756d6-1c311913a2.zip
  .yarn/cache/@carbon-feature-flags-npm-0.7.2-310be5b2ac-67f479a413.zip
  .yarn/cache/@carbon-icon-helpers-npm-10.49.1-c9ba33055a-9e3615888d.zip
  .yarn/cache/@carbon-layout-npm-10.37.4-825bb501fd-af58d24bbc.zip
  .yarn/cache/@ibm-telemetry-js-npm-1.6.0-4dc5a09584-09132a2c10.zip
  .yarn/cache/carbon-components-react-npm-7.59.17-593f3b786c-10b27bf63b.zip
  .yarn/cache/carbon-components-react-npm-7.59.24-7d1f789bf8-8006fbfc21.zip
  .yarn/cache/wicg-inert-npm-3.1.2-786d525c4e-a726f5ca2d.zip
  packages/react/package.json
  packages/styles/package.json
  yarn.lock
Labels: v1

#11945 [web components]: Remove babel/preset-env from build step
  .yarn/cache/babel-extract-comments-npm-1.0.0-66ce3c8bbc-6345c688cc.zip
  .yarn/cache/babel-plugin-syntax-object-rest-spread-npm-6.13.0-9905241ebe-14083f2783.zip
  .yarn/cache/babel-plugin-transform-object-rest-spread-npm-6.26.0-c2b6454d62-d14bd4a90e.zip
  .yarn/cache/strip-comments-npm-1.0.2-4cd3f42d10-494b2e4456.zip
  .yarn/cache/strip-comments-npm-2.0.1-7f4e6e5047-43ea36189e.zip
  packages/carbon-web-components/package.json
  packages/services-store/package.json
  packages/web-components/gulp-tasks/build/modules/scripts.js
  packages/web-components/package.json
  yarn.lock
Labels: dev, package: web components, Ready to merge, dependencies, v2
