Repository carbon-design-system/carbon-for-ibm-dotcom, pull requests merged in 2024-06, with the labels that each got.

#11840 feat(global-banner): add shadow parts
  packages/web-components/src/components/global-banner/global-banner.ts
Labels: shadow parts

#11837 fix(masthead): prevent megamenus from overlaying global banner
  packages/styles/scss/components/masthead/_masthead-megamenu.scss
  packages/styles/scss/components/masthead/_masthead.scss
  packages/web-components/src/components/masthead/masthead-composite.ts
  packages/web-components/src/components/masthead/masthead.scss
Labels: package: styles, package: web components, Ready to merge, owner: Innovation Team, v2

#11844 chore(percy): skip notice-choice component
  packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts
Labels: package: web components, Ready to merge

#11841 feat(leaving-ibm): add shadow parts
  packages/web-components/src/components/global-banner/global-banner.ts
  packages/web-components/src/components/leaving-ibm/leaving-ibm-composite.ts
  packages/web-components/src/components/leaving-ibm/leaving-ibm-modal-body.ts
Labels: shadow parts

#11846 feat(notice-choice): add shadow parts
  packages/web-components/src/components/notice-choice/__stories__/README.stories.mdx
  packages/web-components/src/components/notice-choice/notice-choice.ts
Labels: shadow parts

#11842 fix(left-nav): fix focus trapping
  packages/carbon-web-components/src/components/ui-shell/side-nav.ts
  packages/web-components/src/components/masthead/left-nav-menu-item.ts
  packages/web-components/src/components/masthead/left-nav-menu-section.ts
  packages/web-components/src/components/masthead/left-nav-menu.ts
  packages/web-components/src/components/masthead/left-nav.ts
  packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
  packages/web-components/tests/snapshots/c4d-left-nav-menu.md
Labels: Ready to merge, test: CDN preview

#11839 fix(left-nav): focus trapping
  packages/carbon-web-components/src/components/ui-shell/side-nav.ts
  packages/web-components/src/components/masthead/left-nav-menu-item.ts
  packages/web-components/src/components/masthead/left-nav-menu-section.ts
  packages/web-components/src/components/masthead/left-nav-menu.ts
  packages/web-components/src/components/masthead/left-nav.ts
  packages/web-components/tests/snapshots/dds-left-nav-menu.md
Labels: adopter: AEM, owner: Innovation Team, test: CDN preview

#11853 feat(link-list-section): add CSS shadow parts
  packages/web-components/src/components/link-list-section/link-list-section.ts
  packages/web-components/tests/snapshots/c4d-link-list-section.md
Labels: Ready to merge, shadow parts

#11852 feat(link-list): add CSS shadowparts
  packages/web-components/src/components/link-list/link-list.ts
  packages/web-components/tests/snapshots/c4d-link-list.md
Labels: Ready to merge, shadow parts

#11857 feat(logo-grid): add shadow parts
  packages/web-components/src/components/logo-grid/logo-grid-item.ts
  packages/web-components/src/components/logo-grid/logo-grid.ts
  packages/web-components/tests/snapshots/c4d-logo-grid.md
Labels: shadow parts

#11860 feat(leadspace-block): add shadow parts
  packages/web-components/src/components/leadspace-block/leadspace-block-content.ts
  packages/web-components/src/components/leadspace-block/leadspace-block.ts
  packages/web-components/tests/snapshots/c4d-leadspace-block.md
Labels: Ready to merge, shadow parts

#11863 feat(leadspace-with-search): add shadow parts
  packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
  packages/web-components/tests/snapshots/c4d-search-with-typeahead.md
Labels: shadow parts

#11862 feat(image): add shadow parts
  packages/web-components/src/components/image/image.ts
  packages/web-components/tests/snapshots/c4d-image.md
Labels: shadow parts

#11861 feat(lightbox-media-viewer): add shadow parts
  packages/web-components/src/components/lightbox-media-viewer/__stories__/README.stories.mdx
  packages/web-components/src/components/lightbox-media-viewer/lightbox-image-viewer.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-media-viewer-body.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-media-viewer.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts
  packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player.ts
  packages/web-components/tests/snapshots/c4d-lightbox-image-viewer.md
  packages/web-components/tests/snapshots/c4d-lightbox-video-player-composite.md
  packages/web-components/tests/snapshots/c4d-lightbox-video-player.md
Labels: shadow parts

#11864 feat(leadspace): add shadow parts
  packages/web-components/src/components/leadspace/leadspace.ts
  packages/web-components/tests/snapshots/c4d-leadspace.md
Labels: shadow parts

#11849 feat(quote): add shadow parts
  packages/web-components/src/components/quote/quote.ts
  packages/web-components/tests/snapshots/c4d-callout-quote.md
  packages/web-components/tests/snapshots/c4d-quote.md
Labels: shadow parts

#11850 feat(search-with-typeahead): add shadow parts
  packages/web-components/src/components/search-with-typeahead/scoped-search-dropdown-mobile.ts
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead-item.ts
  packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
Labels: shadow parts

#11865 feat(locale-modal): add shadow parts
  packages/web-components/src/components/locale-modal/locale-item.ts
  packages/web-components/src/components/locale-modal/locale-modal.ts
  packages/web-components/src/components/locale-modal/locale-search.ts
  packages/web-components/src/components/locale-modal/region-item.ts
  packages/web-components/tests/snapshots/c4d-locale-item.md
  packages/web-components/tests/snapshots/c4d-locale-modal.md
  packages/web-components/tests/snapshots/c4d-locale-search.md
Labels: shadow parts

#11845 feat(footer): add footer shadow parts
  packages/web-components/src/components/footer/combo-box.ts
  packages/web-components/src/components/footer/footer-logo.ts
  packages/web-components/src/components/footer/footer-nav-group.ts
  packages/web-components/src/components/footer/footer-nav.ts
  packages/web-components/src/components/footer/footer.ts
  packages/web-components/src/components/footer/legal-nav-cookie-preferences-placeholder.ts
  packages/web-components/src/components/footer/legal-nav.ts
  packages/web-components/src/components/footer/locale-button.ts
  packages/web-components/tests/snapshots/c4d-footer-logo.md
  packages/web-components/tests/snapshots/c4d-footer-nav-group.md
Labels: shadow parts

#11851 feat(structured-list): add shadow parts
  packages/web-components/src/components/structured-list/structured-list-cell.ts
  packages/web-components/src/components/structured-list/structured-list-group.ts
  packages/web-components/src/components/structured-list/structured-list.ts
Labels: shadow parts

#11866 feat(video-player): add shadow parts
  packages/web-components/src/components/video-player/video-player-composite.ts
  packages/web-components/src/components/video-player/video-player.ts
  packages/web-components/tests/snapshots/c4d-video-player-composite.md
  packages/web-components/tests/snapshots/c4d-video-player.md
Labels: shadow parts

#11859 feat(table-of-content): add shadow parts
  packages/web-components/src/components/table-of-contents/table-of-contents.ts
Labels: shadow parts

#11868 feat(sticky-header): allow mixed prefixes with warning
  packages/utilities/src/utilities/StickyHeader/StickyHeader.js
Labels: Ready to merge, owner: Innovation Team, test: CDN preview, v2

#11869 feat(sticky-header): allow mixed prefixes with warning
  packages/utilities/src/utilities/StickyHeader/StickyHeader.js
Labels: Ready to merge, owner: Innovation Team, test: CDN preview, v1

#11882 fix(tabs-extended): prevent stealing focus on page load
  packages/web-components/src/components/tabs-extended/tabs-extended.ts
Labels: package: web components, Ready to merge, adopter: AEM, owner: Innovation Team, test: CDN preview, v1

#11880 feat(pricing-table): add shadow parts
  packages/web-components/src/components/pricing-table/pricing-table-annotation-toggle.ts
  packages/web-components/src/components/pricing-table/pricing-table-cell.ts
  packages/web-components/src/components/pricing-table/pricing-table-header-cell.ts
  packages/web-components/src/components/pricing-table/pricing-table.ts
Labels: shadow parts

#11878 fix(code-snippet): improve copy button overlay presentation
  packages/carbon-web-components/src/components/code-snippet/code-snippet.scss
  packages/carbon-web-components/src/components/code-snippet/code-snippet.ts
Labels: Ready to merge, package: carbon web components, adopter: AEM, owner: Innovation Team, Needs design approval, v1

#11892 feat(accordion): add shadow parts
  packages/carbon-web-components/src/components/accordion/accordion-item-skeleton.ts
  packages/carbon-web-components/src/components/accordion/accordion-item.ts
  packages/carbon-web-components/src/components/accordion/accordion-skeleton.ts
  packages/carbon-web-components/tests/snapshots/cds-combo-box.md
  packages/carbon-web-components/tests/snapshots/cds-dropdown.md
  packages/carbon-web-components/tests/snapshots/cds-multi-select.md
  packages/carbon-web-components/tests/snapshots/cds-number-input.md
  packages/carbon-web-components/tests/snapshots/data-table.md
Labels: package: carbon web components, adopter: AEM, owner: Innovation Team, :eyes: eyes needed, v2, shadow parts

#11896 feat(breadcrumb): add shadow parts
  packages/carbon-web-components/src/components/breadcrumb/breadcrumb-link.ts
  packages/carbon-web-components/src/components/breadcrumb/breadcrumb-skeleton.ts
  packages/carbon-web-components/src/components/breadcrumb/breadcrumb.ts
Labels: shadow parts

#11899 feat(ai-skeleton): add shadow parts
  packages/carbon-web-components/src/components/ai-skeleton/ai-skeleton-icon.ts
  packages/carbon-web-components/src/components/ai-skeleton/ai-skeleton-placeholder.ts
  packages/carbon-web-components/src/components/ai-skeleton/ai-skeleton-text.ts
Labels: shadow parts

#11898 chore(ui-shell): update shadow parts documentation
  packages/carbon-web-components/src/components/ui-shell/header-menu-button.ts
  packages/carbon-web-components/src/components/ui-shell/header-menu.ts
  packages/carbon-web-components/src/components/ui-shell/header-name.ts
  packages/carbon-web-components/src/components/ui-shell/header-nav-item.ts
  packages/carbon-web-components/src/components/ui-shell/header-nav.ts
  packages/carbon-web-components/src/components/ui-shell/side-nav-menu-item.ts
  packages/carbon-web-components/src/components/ui-shell/side-nav-menu.ts
  packages/carbon-web-components/src/components/ui-shell/side-nav.ts
Labels: shadow parts
